//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OdontoSysBusiness.ComprobanteWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webapplication.odontosys.edu.pucp.pe/", ConfigurationName="ComprobanteWS.ComprobanteWA")]
    public interface ComprobanteWA {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webapplication.odontosys.edu.pucp.pe/ComprobanteWA/comprobante_insertarReq" +
            "uest", ReplyAction="http://webapplication.odontosys.edu.pucp.pe/ComprobanteWA/comprobante_insertarRes" +
            "ponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        OdontoSysBusiness.ComprobanteWS.comprobante_insertarResponse comprobante_insertar(OdontoSysBusiness.ComprobanteWS.comprobante_insertarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webapplication.odontosys.edu.pucp.pe/ComprobanteWA/comprobante_insertarReq" +
            "uest", ReplyAction="http://webapplication.odontosys.edu.pucp.pe/ComprobanteWA/comprobante_insertarRes" +
            "ponse")]
        System.Threading.Tasks.Task<OdontoSysBusiness.ComprobanteWS.comprobante_insertarResponse> comprobante_insertarAsync(OdontoSysBusiness.ComprobanteWS.comprobante_insertarRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webapplication.odontosys.edu.pucp.pe/ComprobanteWA/comprobante_eliminarReq" +
            "uest", ReplyAction="http://webapplication.odontosys.edu.pucp.pe/ComprobanteWA/comprobante_eliminarRes" +
            "ponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        OdontoSysBusiness.ComprobanteWS.comprobante_eliminarResponse comprobante_eliminar(OdontoSysBusiness.ComprobanteWS.comprobante_eliminarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webapplication.odontosys.edu.pucp.pe/ComprobanteWA/comprobante_eliminarReq" +
            "uest", ReplyAction="http://webapplication.odontosys.edu.pucp.pe/ComprobanteWA/comprobante_eliminarRes" +
            "ponse")]
        System.Threading.Tasks.Task<OdontoSysBusiness.ComprobanteWS.comprobante_eliminarResponse> comprobante_eliminarAsync(OdontoSysBusiness.ComprobanteWS.comprobante_eliminarRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webapplication.odontosys.edu.pucp.pe/ComprobanteWA/comprobante_modificaReq" +
            "uest", ReplyAction="http://webapplication.odontosys.edu.pucp.pe/ComprobanteWA/comprobante_modificaRes" +
            "ponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        OdontoSysBusiness.ComprobanteWS.comprobante_modificaResponse comprobante_modifica(OdontoSysBusiness.ComprobanteWS.comprobante_modificaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webapplication.odontosys.edu.pucp.pe/ComprobanteWA/comprobante_modificaReq" +
            "uest", ReplyAction="http://webapplication.odontosys.edu.pucp.pe/ComprobanteWA/comprobante_modificaRes" +
            "ponse")]
        System.Threading.Tasks.Task<OdontoSysBusiness.ComprobanteWS.comprobante_modificaResponse> comprobante_modificaAsync(OdontoSysBusiness.ComprobanteWS.comprobante_modificaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webapplication.odontosys.edu.pucp.pe/ComprobanteWA/comprobante_listarTodos" +
            "Request", ReplyAction="http://webapplication.odontosys.edu.pucp.pe/ComprobanteWA/comprobante_listarTodos" +
            "Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        OdontoSysBusiness.ComprobanteWS.comprobante_listarTodosResponse comprobante_listarTodos(OdontoSysBusiness.ComprobanteWS.comprobante_listarTodosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webapplication.odontosys.edu.pucp.pe/ComprobanteWA/comprobante_listarTodos" +
            "Request", ReplyAction="http://webapplication.odontosys.edu.pucp.pe/ComprobanteWA/comprobante_listarTodos" +
            "Response")]
        System.Threading.Tasks.Task<OdontoSysBusiness.ComprobanteWS.comprobante_listarTodosResponse> comprobante_listarTodosAsync(OdontoSysBusiness.ComprobanteWS.comprobante_listarTodosRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webapplication.odontosys.edu.pucp.pe/ComprobanteWA/comprobante_obtenerPorI" +
            "dRequest", ReplyAction="http://webapplication.odontosys.edu.pucp.pe/ComprobanteWA/comprobante_obtenerPorI" +
            "dResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        OdontoSysBusiness.ComprobanteWS.comprobante_obtenerPorIdResponse comprobante_obtenerPorId(OdontoSysBusiness.ComprobanteWS.comprobante_obtenerPorIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webapplication.odontosys.edu.pucp.pe/ComprobanteWA/comprobante_obtenerPorI" +
            "dRequest", ReplyAction="http://webapplication.odontosys.edu.pucp.pe/ComprobanteWA/comprobante_obtenerPorI" +
            "dResponse")]
        System.Threading.Tasks.Task<OdontoSysBusiness.ComprobanteWS.comprobante_obtenerPorIdResponse> comprobante_obtenerPorIdAsync(OdontoSysBusiness.ComprobanteWS.comprobante_obtenerPorIdRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webapplication.odontosys.edu.pucp.pe/ComprobanteWA/comprobante_actualizarT" +
            "otalRequest", ReplyAction="http://webapplication.odontosys.edu.pucp.pe/ComprobanteWA/comprobante_actualizarT" +
            "otalResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        OdontoSysBusiness.ComprobanteWS.comprobante_actualizarTotalResponse comprobante_actualizarTotal(OdontoSysBusiness.ComprobanteWS.comprobante_actualizarTotalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webapplication.odontosys.edu.pucp.pe/ComprobanteWA/comprobante_actualizarT" +
            "otalRequest", ReplyAction="http://webapplication.odontosys.edu.pucp.pe/ComprobanteWA/comprobante_actualizarT" +
            "otalResponse")]
        System.Threading.Tasks.Task<OdontoSysBusiness.ComprobanteWS.comprobante_actualizarTotalResponse> comprobante_actualizarTotalAsync(OdontoSysBusiness.ComprobanteWS.comprobante_actualizarTotalRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webapplication.odontosys.edu.pucp.pe/")]
    public partial class comprobante : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fechaEmisionField;
        
        private string horaEmisionField;
        
        private int idComprobanteField;
        
        private bool idComprobanteFieldSpecified;
        
        private metodoPago metodoDePagoField;
        
        private double totalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string fechaEmision {
            get {
                return this.fechaEmisionField;
            }
            set {
                this.fechaEmisionField = value;
                this.RaisePropertyChanged("fechaEmision");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string horaEmision {
            get {
                return this.horaEmisionField;
            }
            set {
                this.horaEmisionField = value;
                this.RaisePropertyChanged("horaEmision");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idComprobante {
            get {
                return this.idComprobanteField;
            }
            set {
                this.idComprobanteField = value;
                this.RaisePropertyChanged("idComprobante");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idComprobanteSpecified {
            get {
                return this.idComprobanteFieldSpecified;
            }
            set {
                this.idComprobanteFieldSpecified = value;
                this.RaisePropertyChanged("idComprobanteSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public metodoPago metodoDePago {
            get {
                return this.metodoDePagoField;
            }
            set {
                this.metodoDePagoField = value;
                this.RaisePropertyChanged("metodoDePago");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public double total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
                this.RaisePropertyChanged("total");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webapplication.odontosys.edu.pucp.pe/")]
    public partial class metodoPago : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idMetodoPagoField;
        
        private bool idMetodoPagoFieldSpecified;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int idMetodoPago {
            get {
                return this.idMetodoPagoField;
            }
            set {
                this.idMetodoPagoField = value;
                this.RaisePropertyChanged("idMetodoPago");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idMetodoPagoSpecified {
            get {
                return this.idMetodoPagoFieldSpecified;
            }
            set {
                this.idMetodoPagoFieldSpecified = value;
                this.RaisePropertyChanged("idMetodoPagoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="comprobante_insertar", WrapperNamespace="http://webapplication.odontosys.edu.pucp.pe/", IsWrapped=true)]
    public partial class comprobante_insertarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webapplication.odontosys.edu.pucp.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public OdontoSysBusiness.ComprobanteWS.comprobante comprobante;
        
        public comprobante_insertarRequest() {
        }
        
        public comprobante_insertarRequest(OdontoSysBusiness.ComprobanteWS.comprobante comprobante) {
            this.comprobante = comprobante;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="comprobante_insertarResponse", WrapperNamespace="http://webapplication.odontosys.edu.pucp.pe/", IsWrapped=true)]
    public partial class comprobante_insertarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webapplication.odontosys.edu.pucp.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public comprobante_insertarResponse() {
        }
        
        public comprobante_insertarResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="comprobante_eliminar", WrapperNamespace="http://webapplication.odontosys.edu.pucp.pe/", IsWrapped=true)]
    public partial class comprobante_eliminarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webapplication.odontosys.edu.pucp.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public OdontoSysBusiness.ComprobanteWS.comprobante comprobante;
        
        public comprobante_eliminarRequest() {
        }
        
        public comprobante_eliminarRequest(OdontoSysBusiness.ComprobanteWS.comprobante comprobante) {
            this.comprobante = comprobante;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="comprobante_eliminarResponse", WrapperNamespace="http://webapplication.odontosys.edu.pucp.pe/", IsWrapped=true)]
    public partial class comprobante_eliminarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webapplication.odontosys.edu.pucp.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public comprobante_eliminarResponse() {
        }
        
        public comprobante_eliminarResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="comprobante_modifica", WrapperNamespace="http://webapplication.odontosys.edu.pucp.pe/", IsWrapped=true)]
    public partial class comprobante_modificaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webapplication.odontosys.edu.pucp.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public OdontoSysBusiness.ComprobanteWS.comprobante comprobante;
        
        public comprobante_modificaRequest() {
        }
        
        public comprobante_modificaRequest(OdontoSysBusiness.ComprobanteWS.comprobante comprobante) {
            this.comprobante = comprobante;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="comprobante_modificaResponse", WrapperNamespace="http://webapplication.odontosys.edu.pucp.pe/", IsWrapped=true)]
    public partial class comprobante_modificaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webapplication.odontosys.edu.pucp.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public comprobante_modificaResponse() {
        }
        
        public comprobante_modificaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="comprobante_listarTodos", WrapperNamespace="http://webapplication.odontosys.edu.pucp.pe/", IsWrapped=true)]
    public partial class comprobante_listarTodosRequest {
        
        public comprobante_listarTodosRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="comprobante_listarTodosResponse", WrapperNamespace="http://webapplication.odontosys.edu.pucp.pe/", IsWrapped=true)]
    public partial class comprobante_listarTodosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webapplication.odontosys.edu.pucp.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public OdontoSysBusiness.ComprobanteWS.comprobante[] @return;
        
        public comprobante_listarTodosResponse() {
        }
        
        public comprobante_listarTodosResponse(OdontoSysBusiness.ComprobanteWS.comprobante[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="comprobante_obtenerPorId", WrapperNamespace="http://webapplication.odontosys.edu.pucp.pe/", IsWrapped=true)]
    public partial class comprobante_obtenerPorIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webapplication.odontosys.edu.pucp.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public comprobante_obtenerPorIdRequest() {
        }
        
        public comprobante_obtenerPorIdRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="comprobante_obtenerPorIdResponse", WrapperNamespace="http://webapplication.odontosys.edu.pucp.pe/", IsWrapped=true)]
    public partial class comprobante_obtenerPorIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webapplication.odontosys.edu.pucp.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public OdontoSysBusiness.ComprobanteWS.comprobante @return;
        
        public comprobante_obtenerPorIdResponse() {
        }
        
        public comprobante_obtenerPorIdResponse(OdontoSysBusiness.ComprobanteWS.comprobante @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="comprobante_actualizarTotal", WrapperNamespace="http://webapplication.odontosys.edu.pucp.pe/", IsWrapped=true)]
    public partial class comprobante_actualizarTotalRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webapplication.odontosys.edu.pucp.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idCita;
        
        public comprobante_actualizarTotalRequest() {
        }
        
        public comprobante_actualizarTotalRequest(int idCita) {
            this.idCita = idCita;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="comprobante_actualizarTotalResponse", WrapperNamespace="http://webapplication.odontosys.edu.pucp.pe/", IsWrapped=true)]
    public partial class comprobante_actualizarTotalResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webapplication.odontosys.edu.pucp.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public comprobante_actualizarTotalResponse() {
        }
        
        public comprobante_actualizarTotalResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ComprobanteWAChannel : OdontoSysBusiness.ComprobanteWS.ComprobanteWA, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ComprobanteWAClient : System.ServiceModel.ClientBase<OdontoSysBusiness.ComprobanteWS.ComprobanteWA>, OdontoSysBusiness.ComprobanteWS.ComprobanteWA {
        
        public ComprobanteWAClient() {
        }
        
        public ComprobanteWAClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ComprobanteWAClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ComprobanteWAClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ComprobanteWAClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OdontoSysBusiness.ComprobanteWS.comprobante_insertarResponse OdontoSysBusiness.ComprobanteWS.ComprobanteWA.comprobante_insertar(OdontoSysBusiness.ComprobanteWS.comprobante_insertarRequest request) {
            return base.Channel.comprobante_insertar(request);
        }
        
        public int comprobante_insertar(OdontoSysBusiness.ComprobanteWS.comprobante comprobante) {
            OdontoSysBusiness.ComprobanteWS.comprobante_insertarRequest inValue = new OdontoSysBusiness.ComprobanteWS.comprobante_insertarRequest();
            inValue.comprobante = comprobante;
            OdontoSysBusiness.ComprobanteWS.comprobante_insertarResponse retVal = ((OdontoSysBusiness.ComprobanteWS.ComprobanteWA)(this)).comprobante_insertar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OdontoSysBusiness.ComprobanteWS.comprobante_insertarResponse> OdontoSysBusiness.ComprobanteWS.ComprobanteWA.comprobante_insertarAsync(OdontoSysBusiness.ComprobanteWS.comprobante_insertarRequest request) {
            return base.Channel.comprobante_insertarAsync(request);
        }
        
        public System.Threading.Tasks.Task<OdontoSysBusiness.ComprobanteWS.comprobante_insertarResponse> comprobante_insertarAsync(OdontoSysBusiness.ComprobanteWS.comprobante comprobante) {
            OdontoSysBusiness.ComprobanteWS.comprobante_insertarRequest inValue = new OdontoSysBusiness.ComprobanteWS.comprobante_insertarRequest();
            inValue.comprobante = comprobante;
            return ((OdontoSysBusiness.ComprobanteWS.ComprobanteWA)(this)).comprobante_insertarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OdontoSysBusiness.ComprobanteWS.comprobante_eliminarResponse OdontoSysBusiness.ComprobanteWS.ComprobanteWA.comprobante_eliminar(OdontoSysBusiness.ComprobanteWS.comprobante_eliminarRequest request) {
            return base.Channel.comprobante_eliminar(request);
        }
        
        public int comprobante_eliminar(OdontoSysBusiness.ComprobanteWS.comprobante comprobante) {
            OdontoSysBusiness.ComprobanteWS.comprobante_eliminarRequest inValue = new OdontoSysBusiness.ComprobanteWS.comprobante_eliminarRequest();
            inValue.comprobante = comprobante;
            OdontoSysBusiness.ComprobanteWS.comprobante_eliminarResponse retVal = ((OdontoSysBusiness.ComprobanteWS.ComprobanteWA)(this)).comprobante_eliminar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OdontoSysBusiness.ComprobanteWS.comprobante_eliminarResponse> OdontoSysBusiness.ComprobanteWS.ComprobanteWA.comprobante_eliminarAsync(OdontoSysBusiness.ComprobanteWS.comprobante_eliminarRequest request) {
            return base.Channel.comprobante_eliminarAsync(request);
        }
        
        public System.Threading.Tasks.Task<OdontoSysBusiness.ComprobanteWS.comprobante_eliminarResponse> comprobante_eliminarAsync(OdontoSysBusiness.ComprobanteWS.comprobante comprobante) {
            OdontoSysBusiness.ComprobanteWS.comprobante_eliminarRequest inValue = new OdontoSysBusiness.ComprobanteWS.comprobante_eliminarRequest();
            inValue.comprobante = comprobante;
            return ((OdontoSysBusiness.ComprobanteWS.ComprobanteWA)(this)).comprobante_eliminarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OdontoSysBusiness.ComprobanteWS.comprobante_modificaResponse OdontoSysBusiness.ComprobanteWS.ComprobanteWA.comprobante_modifica(OdontoSysBusiness.ComprobanteWS.comprobante_modificaRequest request) {
            return base.Channel.comprobante_modifica(request);
        }
        
        public int comprobante_modifica(OdontoSysBusiness.ComprobanteWS.comprobante comprobante) {
            OdontoSysBusiness.ComprobanteWS.comprobante_modificaRequest inValue = new OdontoSysBusiness.ComprobanteWS.comprobante_modificaRequest();
            inValue.comprobante = comprobante;
            OdontoSysBusiness.ComprobanteWS.comprobante_modificaResponse retVal = ((OdontoSysBusiness.ComprobanteWS.ComprobanteWA)(this)).comprobante_modifica(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OdontoSysBusiness.ComprobanteWS.comprobante_modificaResponse> OdontoSysBusiness.ComprobanteWS.ComprobanteWA.comprobante_modificaAsync(OdontoSysBusiness.ComprobanteWS.comprobante_modificaRequest request) {
            return base.Channel.comprobante_modificaAsync(request);
        }
        
        public System.Threading.Tasks.Task<OdontoSysBusiness.ComprobanteWS.comprobante_modificaResponse> comprobante_modificaAsync(OdontoSysBusiness.ComprobanteWS.comprobante comprobante) {
            OdontoSysBusiness.ComprobanteWS.comprobante_modificaRequest inValue = new OdontoSysBusiness.ComprobanteWS.comprobante_modificaRequest();
            inValue.comprobante = comprobante;
            return ((OdontoSysBusiness.ComprobanteWS.ComprobanteWA)(this)).comprobante_modificaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OdontoSysBusiness.ComprobanteWS.comprobante_listarTodosResponse OdontoSysBusiness.ComprobanteWS.ComprobanteWA.comprobante_listarTodos(OdontoSysBusiness.ComprobanteWS.comprobante_listarTodosRequest request) {
            return base.Channel.comprobante_listarTodos(request);
        }
        
        public OdontoSysBusiness.ComprobanteWS.comprobante[] comprobante_listarTodos() {
            OdontoSysBusiness.ComprobanteWS.comprobante_listarTodosRequest inValue = new OdontoSysBusiness.ComprobanteWS.comprobante_listarTodosRequest();
            OdontoSysBusiness.ComprobanteWS.comprobante_listarTodosResponse retVal = ((OdontoSysBusiness.ComprobanteWS.ComprobanteWA)(this)).comprobante_listarTodos(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OdontoSysBusiness.ComprobanteWS.comprobante_listarTodosResponse> OdontoSysBusiness.ComprobanteWS.ComprobanteWA.comprobante_listarTodosAsync(OdontoSysBusiness.ComprobanteWS.comprobante_listarTodosRequest request) {
            return base.Channel.comprobante_listarTodosAsync(request);
        }
        
        public System.Threading.Tasks.Task<OdontoSysBusiness.ComprobanteWS.comprobante_listarTodosResponse> comprobante_listarTodosAsync() {
            OdontoSysBusiness.ComprobanteWS.comprobante_listarTodosRequest inValue = new OdontoSysBusiness.ComprobanteWS.comprobante_listarTodosRequest();
            return ((OdontoSysBusiness.ComprobanteWS.ComprobanteWA)(this)).comprobante_listarTodosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OdontoSysBusiness.ComprobanteWS.comprobante_obtenerPorIdResponse OdontoSysBusiness.ComprobanteWS.ComprobanteWA.comprobante_obtenerPorId(OdontoSysBusiness.ComprobanteWS.comprobante_obtenerPorIdRequest request) {
            return base.Channel.comprobante_obtenerPorId(request);
        }
        
        public OdontoSysBusiness.ComprobanteWS.comprobante comprobante_obtenerPorId(int id) {
            OdontoSysBusiness.ComprobanteWS.comprobante_obtenerPorIdRequest inValue = new OdontoSysBusiness.ComprobanteWS.comprobante_obtenerPorIdRequest();
            inValue.id = id;
            OdontoSysBusiness.ComprobanteWS.comprobante_obtenerPorIdResponse retVal = ((OdontoSysBusiness.ComprobanteWS.ComprobanteWA)(this)).comprobante_obtenerPorId(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OdontoSysBusiness.ComprobanteWS.comprobante_obtenerPorIdResponse> OdontoSysBusiness.ComprobanteWS.ComprobanteWA.comprobante_obtenerPorIdAsync(OdontoSysBusiness.ComprobanteWS.comprobante_obtenerPorIdRequest request) {
            return base.Channel.comprobante_obtenerPorIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<OdontoSysBusiness.ComprobanteWS.comprobante_obtenerPorIdResponse> comprobante_obtenerPorIdAsync(int id) {
            OdontoSysBusiness.ComprobanteWS.comprobante_obtenerPorIdRequest inValue = new OdontoSysBusiness.ComprobanteWS.comprobante_obtenerPorIdRequest();
            inValue.id = id;
            return ((OdontoSysBusiness.ComprobanteWS.ComprobanteWA)(this)).comprobante_obtenerPorIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OdontoSysBusiness.ComprobanteWS.comprobante_actualizarTotalResponse OdontoSysBusiness.ComprobanteWS.ComprobanteWA.comprobante_actualizarTotal(OdontoSysBusiness.ComprobanteWS.comprobante_actualizarTotalRequest request) {
            return base.Channel.comprobante_actualizarTotal(request);
        }
        
        public int comprobante_actualizarTotal(int idCita) {
            OdontoSysBusiness.ComprobanteWS.comprobante_actualizarTotalRequest inValue = new OdontoSysBusiness.ComprobanteWS.comprobante_actualizarTotalRequest();
            inValue.idCita = idCita;
            OdontoSysBusiness.ComprobanteWS.comprobante_actualizarTotalResponse retVal = ((OdontoSysBusiness.ComprobanteWS.ComprobanteWA)(this)).comprobante_actualizarTotal(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OdontoSysBusiness.ComprobanteWS.comprobante_actualizarTotalResponse> OdontoSysBusiness.ComprobanteWS.ComprobanteWA.comprobante_actualizarTotalAsync(OdontoSysBusiness.ComprobanteWS.comprobante_actualizarTotalRequest request) {
            return base.Channel.comprobante_actualizarTotalAsync(request);
        }
        
        public System.Threading.Tasks.Task<OdontoSysBusiness.ComprobanteWS.comprobante_actualizarTotalResponse> comprobante_actualizarTotalAsync(int idCita) {
            OdontoSysBusiness.ComprobanteWS.comprobante_actualizarTotalRequest inValue = new OdontoSysBusiness.ComprobanteWS.comprobante_actualizarTotalRequest();
            inValue.idCita = idCita;
            return ((OdontoSysBusiness.ComprobanteWS.ComprobanteWA)(this)).comprobante_actualizarTotalAsync(inValue);
        }
    }
}
