//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace OdontoSysBusiness.pacienteWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://wa.odontosys.com/", ConfigurationName="pacienteWS.Pacientes")]
    public interface Pacientes {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://wa.odontosys.com/Pacientes/eliminarPacienteRequest", ReplyAction="http://wa.odontosys.com/Pacientes/eliminarPacienteResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        OdontoSysBusiness.pacienteWS.eliminarPacienteResponse eliminarPaciente(OdontoSysBusiness.pacienteWS.eliminarPacienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wa.odontosys.com/Pacientes/eliminarPacienteRequest", ReplyAction="http://wa.odontosys.com/Pacientes/eliminarPacienteResponse")]
        System.Threading.Tasks.Task<OdontoSysBusiness.pacienteWS.eliminarPacienteResponse> eliminarPacienteAsync(OdontoSysBusiness.pacienteWS.eliminarPacienteRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://wa.odontosys.com/Pacientes/listarPacientesRequest", ReplyAction="http://wa.odontosys.com/Pacientes/listarPacientesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        OdontoSysBusiness.pacienteWS.listarPacientesResponse listarPacientes(OdontoSysBusiness.pacienteWS.listarPacientesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wa.odontosys.com/Pacientes/listarPacientesRequest", ReplyAction="http://wa.odontosys.com/Pacientes/listarPacientesResponse")]
        System.Threading.Tasks.Task<OdontoSysBusiness.pacienteWS.listarPacientesResponse> listarPacientesAsync(OdontoSysBusiness.pacienteWS.listarPacientesRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://wa.odontosys.com/Pacientes/pa_obtenerPorIDRequest", ReplyAction="http://wa.odontosys.com/Pacientes/pa_obtenerPorIDResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        OdontoSysBusiness.pacienteWS.pa_obtenerPorIDResponse pa_obtenerPorID(OdontoSysBusiness.pacienteWS.pa_obtenerPorIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wa.odontosys.com/Pacientes/pa_obtenerPorIDRequest", ReplyAction="http://wa.odontosys.com/Pacientes/pa_obtenerPorIDResponse")]
        System.Threading.Tasks.Task<OdontoSysBusiness.pacienteWS.pa_obtenerPorIDResponse> pa_obtenerPorIDAsync(OdontoSysBusiness.pacienteWS.pa_obtenerPorIDRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://wa.odontosys.com/Pacientes/modificarPacienteRequest", ReplyAction="http://wa.odontosys.com/Pacientes/modificarPacienteResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        OdontoSysBusiness.pacienteWS.modificarPacienteResponse modificarPaciente(OdontoSysBusiness.pacienteWS.modificarPacienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wa.odontosys.com/Pacientes/modificarPacienteRequest", ReplyAction="http://wa.odontosys.com/Pacientes/modificarPacienteResponse")]
        System.Threading.Tasks.Task<OdontoSysBusiness.pacienteWS.modificarPacienteResponse> modificarPacienteAsync(OdontoSysBusiness.pacienteWS.modificarPacienteRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://wa.odontosys.com/Pacientes/insertarPacienteRequest", ReplyAction="http://wa.odontosys.com/Pacientes/insertarPacienteResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        OdontoSysBusiness.pacienteWS.insertarPacienteResponse insertarPaciente(OdontoSysBusiness.pacienteWS.insertarPacienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wa.odontosys.com/Pacientes/insertarPacienteRequest", ReplyAction="http://wa.odontosys.com/Pacientes/insertarPacienteResponse")]
        System.Threading.Tasks.Task<OdontoSysBusiness.pacienteWS.insertarPacienteResponse> insertarPacienteAsync(OdontoSysBusiness.pacienteWS.insertarPacienteRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://wa.odontosys.com/Pacientes/pa_buscarPorUsuarioRequest", ReplyAction="http://wa.odontosys.com/Pacientes/pa_buscarPorUsuarioResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        OdontoSysBusiness.pacienteWS.pa_buscarPorUsuarioResponse pa_buscarPorUsuario(OdontoSysBusiness.pacienteWS.pa_buscarPorUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wa.odontosys.com/Pacientes/pa_buscarPorUsuarioRequest", ReplyAction="http://wa.odontosys.com/Pacientes/pa_buscarPorUsuarioResponse")]
        System.Threading.Tasks.Task<OdontoSysBusiness.pacienteWS.pa_buscarPorUsuarioResponse> pa_buscarPorUsuarioAsync(OdontoSysBusiness.pacienteWS.pa_buscarPorUsuarioRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wa.odontosys.com/")]
    public partial class paciente : persona {
        
        private cita[] citasField;
        
        private int idPacienteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("citas", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public cita[] citas {
            get {
                return this.citasField;
            }
            set {
                this.citasField = value;
                this.RaisePropertyChanged("citas");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int idPaciente {
            get {
                return this.idPacienteField;
            }
            set {
                this.idPacienteField = value;
                this.RaisePropertyChanged("idPaciente");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wa.odontosys.com/")]
    public partial class cita : object, System.ComponentModel.INotifyPropertyChanged {
        
        private comprobante comprobanteField;
        
        private estadoCita estadoField;
        
        private bool estadoFieldSpecified;
        
        private localDate fechaField;
        
        private localTime horaInicioField;
        
        private int idCitaField;
        
        private odontologo odontologoField;
        
        private paciente pacienteField;
        
        private double puntuacionField;
        
        private recepcionista recepcionistaField;
        
        private detalleTratamiento[] tratamientosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public comprobante comprobante {
            get {
                return this.comprobanteField;
            }
            set {
                this.comprobanteField = value;
                this.RaisePropertyChanged("comprobante");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public estadoCita estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool estadoSpecified {
            get {
                return this.estadoFieldSpecified;
            }
            set {
                this.estadoFieldSpecified = value;
                this.RaisePropertyChanged("estadoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public localDate fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
                this.RaisePropertyChanged("fecha");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public localTime horaInicio {
            get {
                return this.horaInicioField;
            }
            set {
                this.horaInicioField = value;
                this.RaisePropertyChanged("horaInicio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int idCita {
            get {
                return this.idCitaField;
            }
            set {
                this.idCitaField = value;
                this.RaisePropertyChanged("idCita");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public odontologo odontologo {
            get {
                return this.odontologoField;
            }
            set {
                this.odontologoField = value;
                this.RaisePropertyChanged("odontologo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public paciente paciente {
            get {
                return this.pacienteField;
            }
            set {
                this.pacienteField = value;
                this.RaisePropertyChanged("paciente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public double puntuacion {
            get {
                return this.puntuacionField;
            }
            set {
                this.puntuacionField = value;
                this.RaisePropertyChanged("puntuacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public recepcionista recepcionista {
            get {
                return this.recepcionistaField;
            }
            set {
                this.recepcionistaField = value;
                this.RaisePropertyChanged("recepcionista");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("tratamientos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=9)]
        public detalleTratamiento[] tratamientos {
            get {
                return this.tratamientosField;
            }
            set {
                this.tratamientosField = value;
                this.RaisePropertyChanged("tratamientos");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wa.odontosys.com/")]
    public partial class comprobante : object, System.ComponentModel.INotifyPropertyChanged {
        
        private localDate fechaEmisionField;
        
        private localTime horaEmisionField;
        
        private int idComprobanteField;
        
        private metodoPago metodoDePagoField;
        
        private double totalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public localDate fechaEmision {
            get {
                return this.fechaEmisionField;
            }
            set {
                this.fechaEmisionField = value;
                this.RaisePropertyChanged("fechaEmision");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public localTime horaEmision {
            get {
                return this.horaEmisionField;
            }
            set {
                this.horaEmisionField = value;
                this.RaisePropertyChanged("horaEmision");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idComprobante {
            get {
                return this.idComprobanteField;
            }
            set {
                this.idComprobanteField = value;
                this.RaisePropertyChanged("idComprobante");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public metodoPago metodoDePago {
            get {
                return this.metodoDePagoField;
            }
            set {
                this.metodoDePagoField = value;
                this.RaisePropertyChanged("metodoDePago");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public double total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
                this.RaisePropertyChanged("total");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wa.odontosys.com/")]
    public partial class localDate : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wa.odontosys.com/")]
    public partial class tratamiento : object, System.ComponentModel.INotifyPropertyChanged {
        
        private double costoField;
        
        private string descripcionField;
        
        private especialidad especialidadField;
        
        private int idTratamientoField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public double costo {
            get {
                return this.costoField;
            }
            set {
                this.costoField = value;
                this.RaisePropertyChanged("costo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public especialidad especialidad {
            get {
                return this.especialidadField;
            }
            set {
                this.especialidadField = value;
                this.RaisePropertyChanged("especialidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int idTratamiento {
            get {
                return this.idTratamientoField;
            }
            set {
                this.idTratamientoField = value;
                this.RaisePropertyChanged("idTratamiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wa.odontosys.com/")]
    public partial class especialidad : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idEspecialidadField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int idEspecialidad {
            get {
                return this.idEspecialidadField;
            }
            set {
                this.idEspecialidadField = value;
                this.RaisePropertyChanged("idEspecialidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wa.odontosys.com/")]
    public partial class detalleTratamiento : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int cantidadField;
        
        private int idCitaField;
        
        private double subtotalField;
        
        private tratamiento tratamientoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int cantidad {
            get {
                return this.cantidadField;
            }
            set {
                this.cantidadField = value;
                this.RaisePropertyChanged("cantidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int idCita {
            get {
                return this.idCitaField;
            }
            set {
                this.idCitaField = value;
                this.RaisePropertyChanged("idCita");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public double subtotal {
            get {
                return this.subtotalField;
            }
            set {
                this.subtotalField = value;
                this.RaisePropertyChanged("subtotal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public tratamiento tratamiento {
            get {
                return this.tratamientoField;
            }
            set {
                this.tratamientoField = value;
                this.RaisePropertyChanged("tratamiento");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wa.odontosys.com/")]
    public partial class turno : object, System.ComponentModel.INotifyPropertyChanged {
        
        private diaSemana diaSemanaField;
        
        private bool diaSemanaFieldSpecified;
        
        private localTime horaFinField;
        
        private localTime horaInicioField;
        
        private int idTurnoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public diaSemana diaSemana {
            get {
                return this.diaSemanaField;
            }
            set {
                this.diaSemanaField = value;
                this.RaisePropertyChanged("diaSemana");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool diaSemanaSpecified {
            get {
                return this.diaSemanaFieldSpecified;
            }
            set {
                this.diaSemanaFieldSpecified = value;
                this.RaisePropertyChanged("diaSemanaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public localTime horaFin {
            get {
                return this.horaFinField;
            }
            set {
                this.horaFinField = value;
                this.RaisePropertyChanged("horaFin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public localTime horaInicio {
            get {
                return this.horaInicioField;
            }
            set {
                this.horaInicioField = value;
                this.RaisePropertyChanged("horaInicio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int idTurno {
            get {
                return this.idTurnoField;
            }
            set {
                this.idTurnoField = value;
                this.RaisePropertyChanged("idTurno");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wa.odontosys.com/")]
    public enum diaSemana {
        
        /// <remarks/>
        MONDAY,
        
        /// <remarks/>
        TUESDAY,
        
        /// <remarks/>
        WEDNESDAY,
        
        /// <remarks/>
        THURSDAY,
        
        /// <remarks/>
        FRIDAY,
        
        /// <remarks/>
        SATURDAY,
        
        /// <remarks/>
        SUNDAY,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wa.odontosys.com/")]
    public partial class localTime : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wa.odontosys.com/")]
    public partial class sala : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idSalaField;
        
        private string numeroField;
        
        private int pisoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int idSala {
            get {
                return this.idSalaField;
            }
            set {
                this.idSalaField = value;
                this.RaisePropertyChanged("idSala");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
                this.RaisePropertyChanged("numero");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int piso {
            get {
                return this.pisoField;
            }
            set {
                this.pisoField = value;
                this.RaisePropertyChanged("piso");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wa.odontosys.com/")]
    public partial class metodoPago : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idMetodoPagoField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int idMetodoPago {
            get {
                return this.idMetodoPagoField;
            }
            set {
                this.idMetodoPagoField = value;
                this.RaisePropertyChanged("idMetodoPago");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(recepcionista))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(odontologo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(paciente))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wa.odontosys.com/")]
    public abstract partial class persona : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string apellidosField;
        
        private string contrasenhaField;
        
        private string correoField;
        
        private string nombreField;
        
        private string nombreUsuarioField;
        
        private string numeroDocumentoField;
        
        private string telefonoField;
        
        private tipoDocumento tipoDocumentoField;
        
        private bool tipoDocumentoFieldSpecified;
        
        private tipoUsuario tipoUsuarioField;
        
        private bool tipoUsuarioFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string apellidos {
            get {
                return this.apellidosField;
            }
            set {
                this.apellidosField = value;
                this.RaisePropertyChanged("apellidos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string contrasenha {
            get {
                return this.contrasenhaField;
            }
            set {
                this.contrasenhaField = value;
                this.RaisePropertyChanged("contrasenha");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string correo {
            get {
                return this.correoField;
            }
            set {
                this.correoField = value;
                this.RaisePropertyChanged("correo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string nombreUsuario {
            get {
                return this.nombreUsuarioField;
            }
            set {
                this.nombreUsuarioField = value;
                this.RaisePropertyChanged("nombreUsuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string numeroDocumento {
            get {
                return this.numeroDocumentoField;
            }
            set {
                this.numeroDocumentoField = value;
                this.RaisePropertyChanged("numeroDocumento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("telefono");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public tipoDocumento tipoDocumento {
            get {
                return this.tipoDocumentoField;
            }
            set {
                this.tipoDocumentoField = value;
                this.RaisePropertyChanged("tipoDocumento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipoDocumentoSpecified {
            get {
                return this.tipoDocumentoFieldSpecified;
            }
            set {
                this.tipoDocumentoFieldSpecified = value;
                this.RaisePropertyChanged("tipoDocumentoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public tipoUsuario tipoUsuario {
            get {
                return this.tipoUsuarioField;
            }
            set {
                this.tipoUsuarioField = value;
                this.RaisePropertyChanged("tipoUsuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipoUsuarioSpecified {
            get {
                return this.tipoUsuarioFieldSpecified;
            }
            set {
                this.tipoUsuarioFieldSpecified = value;
                this.RaisePropertyChanged("tipoUsuarioSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wa.odontosys.com/")]
    public enum tipoDocumento {
        
        /// <remarks/>
        DNI,
        
        /// <remarks/>
        CARNE_DE_EXTRANJERIA,
        
        /// <remarks/>
        PASAPORTE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wa.odontosys.com/")]
    public enum tipoUsuario {
        
        /// <remarks/>
        PLACEHOLDER,
        
        /// <remarks/>
        PACIENTE,
        
        /// <remarks/>
        ODONTOLOGO,
        
        /// <remarks/>
        RECEPCIONISTA,
        
        /// <remarks/>
        ADMINISTRADOR,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wa.odontosys.com/")]
    public partial class recepcionista : persona {
        
        private int idRecepcionistaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int idRecepcionista {
            get {
                return this.idRecepcionistaField;
            }
            set {
                this.idRecepcionistaField = value;
                this.RaisePropertyChanged("idRecepcionista");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wa.odontosys.com/")]
    public partial class odontologo : persona {
        
        private cita[] citasField;
        
        private sala consultorioField;
        
        private especialidad especialidadField;
        
        private int idOdontologoField;
        
        private double puntuacionPromedioField;
        
        private turno[] turnosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("citas", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public cita[] citas {
            get {
                return this.citasField;
            }
            set {
                this.citasField = value;
                this.RaisePropertyChanged("citas");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public sala consultorio {
            get {
                return this.consultorioField;
            }
            set {
                this.consultorioField = value;
                this.RaisePropertyChanged("consultorio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public especialidad especialidad {
            get {
                return this.especialidadField;
            }
            set {
                this.especialidadField = value;
                this.RaisePropertyChanged("especialidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int idOdontologo {
            get {
                return this.idOdontologoField;
            }
            set {
                this.idOdontologoField = value;
                this.RaisePropertyChanged("idOdontologo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public double puntuacionPromedio {
            get {
                return this.puntuacionPromedioField;
            }
            set {
                this.puntuacionPromedioField = value;
                this.RaisePropertyChanged("puntuacionPromedio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("turnos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public turno[] turnos {
            get {
                return this.turnosField;
            }
            set {
                this.turnosField = value;
                this.RaisePropertyChanged("turnos");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wa.odontosys.com/")]
    public enum estadoCita {
        
        /// <remarks/>
        RESERVADA,
        
        /// <remarks/>
        ATENDIDA,
        
        /// <remarks/>
        CANCELADA,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarPaciente", WrapperNamespace="http://wa.odontosys.com/", IsWrapped=true)]
    public partial class eliminarPacienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wa.odontosys.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public OdontoSysBusiness.pacienteWS.paciente paciente;
        
        public eliminarPacienteRequest() {
        }
        
        public eliminarPacienteRequest(OdontoSysBusiness.pacienteWS.paciente paciente) {
            this.paciente = paciente;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarPacienteResponse", WrapperNamespace="http://wa.odontosys.com/", IsWrapped=true)]
    public partial class eliminarPacienteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wa.odontosys.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarPacienteResponse() {
        }
        
        public eliminarPacienteResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarPacientes", WrapperNamespace="http://wa.odontosys.com/", IsWrapped=true)]
    public partial class listarPacientesRequest {
        
        public listarPacientesRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarPacientesResponse", WrapperNamespace="http://wa.odontosys.com/", IsWrapped=true)]
    public partial class listarPacientesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wa.odontosys.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public OdontoSysBusiness.pacienteWS.paciente[] @return;
        
        public listarPacientesResponse() {
        }
        
        public listarPacientesResponse(OdontoSysBusiness.pacienteWS.paciente[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="pa_obtenerPorID", WrapperNamespace="http://wa.odontosys.com/", IsWrapped=true)]
    public partial class pa_obtenerPorIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wa.odontosys.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int pacienteId;
        
        public pa_obtenerPorIDRequest() {
        }
        
        public pa_obtenerPorIDRequest(int pacienteId) {
            this.pacienteId = pacienteId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="pa_obtenerPorIDResponse", WrapperNamespace="http://wa.odontosys.com/", IsWrapped=true)]
    public partial class pa_obtenerPorIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wa.odontosys.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public OdontoSysBusiness.pacienteWS.paciente @return;
        
        public pa_obtenerPorIDResponse() {
        }
        
        public pa_obtenerPorIDResponse(OdontoSysBusiness.pacienteWS.paciente @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarPaciente", WrapperNamespace="http://wa.odontosys.com/", IsWrapped=true)]
    public partial class modificarPacienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wa.odontosys.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public OdontoSysBusiness.pacienteWS.paciente paciente;
        
        public modificarPacienteRequest() {
        }
        
        public modificarPacienteRequest(OdontoSysBusiness.pacienteWS.paciente paciente) {
            this.paciente = paciente;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarPacienteResponse", WrapperNamespace="http://wa.odontosys.com/", IsWrapped=true)]
    public partial class modificarPacienteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wa.odontosys.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarPacienteResponse() {
        }
        
        public modificarPacienteResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarPaciente", WrapperNamespace="http://wa.odontosys.com/", IsWrapped=true)]
    public partial class insertarPacienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wa.odontosys.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public OdontoSysBusiness.pacienteWS.paciente paciente;
        
        public insertarPacienteRequest() {
        }
        
        public insertarPacienteRequest(OdontoSysBusiness.pacienteWS.paciente paciente) {
            this.paciente = paciente;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarPacienteResponse", WrapperNamespace="http://wa.odontosys.com/", IsWrapped=true)]
    public partial class insertarPacienteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wa.odontosys.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarPacienteResponse() {
        }
        
        public insertarPacienteResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="pa_buscarPorUsuario", WrapperNamespace="http://wa.odontosys.com/", IsWrapped=true)]
    public partial class pa_buscarPorUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wa.odontosys.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombreUsuario;
        
        public pa_buscarPorUsuarioRequest() {
        }
        
        public pa_buscarPorUsuarioRequest(string nombreUsuario) {
            this.nombreUsuario = nombreUsuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="pa_buscarPorUsuarioResponse", WrapperNamespace="http://wa.odontosys.com/", IsWrapped=true)]
    public partial class pa_buscarPorUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wa.odontosys.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public OdontoSysBusiness.pacienteWS.paciente @return;
        
        public pa_buscarPorUsuarioResponse() {
        }
        
        public pa_buscarPorUsuarioResponse(OdontoSysBusiness.pacienteWS.paciente @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PacientesChannel : OdontoSysBusiness.pacienteWS.Pacientes, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PacientesClient : System.ServiceModel.ClientBase<OdontoSysBusiness.pacienteWS.Pacientes>, OdontoSysBusiness.pacienteWS.Pacientes {
        
        public PacientesClient() {
        }
        
        public PacientesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PacientesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PacientesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PacientesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OdontoSysBusiness.pacienteWS.eliminarPacienteResponse OdontoSysBusiness.pacienteWS.Pacientes.eliminarPaciente(OdontoSysBusiness.pacienteWS.eliminarPacienteRequest request) {
            return base.Channel.eliminarPaciente(request);
        }
        
        public int eliminarPaciente(OdontoSysBusiness.pacienteWS.paciente paciente) {
            OdontoSysBusiness.pacienteWS.eliminarPacienteRequest inValue = new OdontoSysBusiness.pacienteWS.eliminarPacienteRequest();
            inValue.paciente = paciente;
            OdontoSysBusiness.pacienteWS.eliminarPacienteResponse retVal = ((OdontoSysBusiness.pacienteWS.Pacientes)(this)).eliminarPaciente(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OdontoSysBusiness.pacienteWS.eliminarPacienteResponse> OdontoSysBusiness.pacienteWS.Pacientes.eliminarPacienteAsync(OdontoSysBusiness.pacienteWS.eliminarPacienteRequest request) {
            return base.Channel.eliminarPacienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<OdontoSysBusiness.pacienteWS.eliminarPacienteResponse> eliminarPacienteAsync(OdontoSysBusiness.pacienteWS.paciente paciente) {
            OdontoSysBusiness.pacienteWS.eliminarPacienteRequest inValue = new OdontoSysBusiness.pacienteWS.eliminarPacienteRequest();
            inValue.paciente = paciente;
            return ((OdontoSysBusiness.pacienteWS.Pacientes)(this)).eliminarPacienteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OdontoSysBusiness.pacienteWS.listarPacientesResponse OdontoSysBusiness.pacienteWS.Pacientes.listarPacientes(OdontoSysBusiness.pacienteWS.listarPacientesRequest request) {
            return base.Channel.listarPacientes(request);
        }
        
        public OdontoSysBusiness.pacienteWS.paciente[] listarPacientes() {
            OdontoSysBusiness.pacienteWS.listarPacientesRequest inValue = new OdontoSysBusiness.pacienteWS.listarPacientesRequest();
            OdontoSysBusiness.pacienteWS.listarPacientesResponse retVal = ((OdontoSysBusiness.pacienteWS.Pacientes)(this)).listarPacientes(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OdontoSysBusiness.pacienteWS.listarPacientesResponse> OdontoSysBusiness.pacienteWS.Pacientes.listarPacientesAsync(OdontoSysBusiness.pacienteWS.listarPacientesRequest request) {
            return base.Channel.listarPacientesAsync(request);
        }
        
        public System.Threading.Tasks.Task<OdontoSysBusiness.pacienteWS.listarPacientesResponse> listarPacientesAsync() {
            OdontoSysBusiness.pacienteWS.listarPacientesRequest inValue = new OdontoSysBusiness.pacienteWS.listarPacientesRequest();
            return ((OdontoSysBusiness.pacienteWS.Pacientes)(this)).listarPacientesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OdontoSysBusiness.pacienteWS.pa_obtenerPorIDResponse OdontoSysBusiness.pacienteWS.Pacientes.pa_obtenerPorID(OdontoSysBusiness.pacienteWS.pa_obtenerPorIDRequest request) {
            return base.Channel.pa_obtenerPorID(request);
        }
        
        public OdontoSysBusiness.pacienteWS.paciente pa_obtenerPorID(int pacienteId) {
            OdontoSysBusiness.pacienteWS.pa_obtenerPorIDRequest inValue = new OdontoSysBusiness.pacienteWS.pa_obtenerPorIDRequest();
            inValue.pacienteId = pacienteId;
            OdontoSysBusiness.pacienteWS.pa_obtenerPorIDResponse retVal = ((OdontoSysBusiness.pacienteWS.Pacientes)(this)).pa_obtenerPorID(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OdontoSysBusiness.pacienteWS.pa_obtenerPorIDResponse> OdontoSysBusiness.pacienteWS.Pacientes.pa_obtenerPorIDAsync(OdontoSysBusiness.pacienteWS.pa_obtenerPorIDRequest request) {
            return base.Channel.pa_obtenerPorIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<OdontoSysBusiness.pacienteWS.pa_obtenerPorIDResponse> pa_obtenerPorIDAsync(int pacienteId) {
            OdontoSysBusiness.pacienteWS.pa_obtenerPorIDRequest inValue = new OdontoSysBusiness.pacienteWS.pa_obtenerPorIDRequest();
            inValue.pacienteId = pacienteId;
            return ((OdontoSysBusiness.pacienteWS.Pacientes)(this)).pa_obtenerPorIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OdontoSysBusiness.pacienteWS.modificarPacienteResponse OdontoSysBusiness.pacienteWS.Pacientes.modificarPaciente(OdontoSysBusiness.pacienteWS.modificarPacienteRequest request) {
            return base.Channel.modificarPaciente(request);
        }
        
        public int modificarPaciente(OdontoSysBusiness.pacienteWS.paciente paciente) {
            OdontoSysBusiness.pacienteWS.modificarPacienteRequest inValue = new OdontoSysBusiness.pacienteWS.modificarPacienteRequest();
            inValue.paciente = paciente;
            OdontoSysBusiness.pacienteWS.modificarPacienteResponse retVal = ((OdontoSysBusiness.pacienteWS.Pacientes)(this)).modificarPaciente(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OdontoSysBusiness.pacienteWS.modificarPacienteResponse> OdontoSysBusiness.pacienteWS.Pacientes.modificarPacienteAsync(OdontoSysBusiness.pacienteWS.modificarPacienteRequest request) {
            return base.Channel.modificarPacienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<OdontoSysBusiness.pacienteWS.modificarPacienteResponse> modificarPacienteAsync(OdontoSysBusiness.pacienteWS.paciente paciente) {
            OdontoSysBusiness.pacienteWS.modificarPacienteRequest inValue = new OdontoSysBusiness.pacienteWS.modificarPacienteRequest();
            inValue.paciente = paciente;
            return ((OdontoSysBusiness.pacienteWS.Pacientes)(this)).modificarPacienteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OdontoSysBusiness.pacienteWS.insertarPacienteResponse OdontoSysBusiness.pacienteWS.Pacientes.insertarPaciente(OdontoSysBusiness.pacienteWS.insertarPacienteRequest request) {
            return base.Channel.insertarPaciente(request);
        }
        
        public int insertarPaciente(OdontoSysBusiness.pacienteWS.paciente paciente) {
            OdontoSysBusiness.pacienteWS.insertarPacienteRequest inValue = new OdontoSysBusiness.pacienteWS.insertarPacienteRequest();
            inValue.paciente = paciente;
            OdontoSysBusiness.pacienteWS.insertarPacienteResponse retVal = ((OdontoSysBusiness.pacienteWS.Pacientes)(this)).insertarPaciente(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OdontoSysBusiness.pacienteWS.insertarPacienteResponse> OdontoSysBusiness.pacienteWS.Pacientes.insertarPacienteAsync(OdontoSysBusiness.pacienteWS.insertarPacienteRequest request) {
            return base.Channel.insertarPacienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<OdontoSysBusiness.pacienteWS.insertarPacienteResponse> insertarPacienteAsync(OdontoSysBusiness.pacienteWS.paciente paciente) {
            OdontoSysBusiness.pacienteWS.insertarPacienteRequest inValue = new OdontoSysBusiness.pacienteWS.insertarPacienteRequest();
            inValue.paciente = paciente;
            return ((OdontoSysBusiness.pacienteWS.Pacientes)(this)).insertarPacienteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OdontoSysBusiness.pacienteWS.pa_buscarPorUsuarioResponse OdontoSysBusiness.pacienteWS.Pacientes.pa_buscarPorUsuario(OdontoSysBusiness.pacienteWS.pa_buscarPorUsuarioRequest request) {
            return base.Channel.pa_buscarPorUsuario(request);
        }
        
        public OdontoSysBusiness.pacienteWS.paciente pa_buscarPorUsuario(string nombreUsuario) {
            OdontoSysBusiness.pacienteWS.pa_buscarPorUsuarioRequest inValue = new OdontoSysBusiness.pacienteWS.pa_buscarPorUsuarioRequest();
            inValue.nombreUsuario = nombreUsuario;
            OdontoSysBusiness.pacienteWS.pa_buscarPorUsuarioResponse retVal = ((OdontoSysBusiness.pacienteWS.Pacientes)(this)).pa_buscarPorUsuario(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OdontoSysBusiness.pacienteWS.pa_buscarPorUsuarioResponse> OdontoSysBusiness.pacienteWS.Pacientes.pa_buscarPorUsuarioAsync(OdontoSysBusiness.pacienteWS.pa_buscarPorUsuarioRequest request) {
            return base.Channel.pa_buscarPorUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<OdontoSysBusiness.pacienteWS.pa_buscarPorUsuarioResponse> pa_buscarPorUsuarioAsync(string nombreUsuario) {
            OdontoSysBusiness.pacienteWS.pa_buscarPorUsuarioRequest inValue = new OdontoSysBusiness.pacienteWS.pa_buscarPorUsuarioRequest();
            inValue.nombreUsuario = nombreUsuario;
            return ((OdontoSysBusiness.pacienteWS.Pacientes)(this)).pa_buscarPorUsuarioAsync(inValue);
        }
    }
}
