//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OdontoSysWebApplication.DetalleTratamientoWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webapplication.odontosys.edu.pucp.pe/", ConfigurationName="DetalleTratamientoWS.DetalleTratamientoWA")]
    public interface DetalleTratamientoWA {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webapplication.odontosys.edu.pucp.pe/DetalleTratamientoWA/detalleTratamien" +
            "to_insertarRequest", ReplyAction="http://webapplication.odontosys.edu.pucp.pe/DetalleTratamientoWA/detalleTratamien" +
            "to_insertarResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        OdontoSysWebApplication.DetalleTratamientoWS.detalleTratamiento_insertarResponse detalleTratamiento_insertar(OdontoSysWebApplication.DetalleTratamientoWS.detalleTratamiento_insertarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webapplication.odontosys.edu.pucp.pe/DetalleTratamientoWA/detalleTratamien" +
            "to_insertarRequest", ReplyAction="http://webapplication.odontosys.edu.pucp.pe/DetalleTratamientoWA/detalleTratamien" +
            "to_insertarResponse")]
        System.Threading.Tasks.Task<OdontoSysWebApplication.DetalleTratamientoWS.detalleTratamiento_insertarResponse> detalleTratamiento_insertarAsync(OdontoSysWebApplication.DetalleTratamientoWS.detalleTratamiento_insertarRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webapplication.odontosys.edu.pucp.pe/DetalleTratamientoWA/detalleTratamien" +
            "to_listarTodosRequest", ReplyAction="http://webapplication.odontosys.edu.pucp.pe/DetalleTratamientoWA/detalleTratamien" +
            "to_listarTodosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        OdontoSysWebApplication.DetalleTratamientoWS.detalleTratamiento_listarTodosResponse detalleTratamiento_listarTodos(OdontoSysWebApplication.DetalleTratamientoWS.detalleTratamiento_listarTodosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webapplication.odontosys.edu.pucp.pe/DetalleTratamientoWA/detalleTratamien" +
            "to_listarTodosRequest", ReplyAction="http://webapplication.odontosys.edu.pucp.pe/DetalleTratamientoWA/detalleTratamien" +
            "to_listarTodosResponse")]
        System.Threading.Tasks.Task<OdontoSysWebApplication.DetalleTratamientoWS.detalleTratamiento_listarTodosResponse> detalleTratamiento_listarTodosAsync(OdontoSysWebApplication.DetalleTratamientoWS.detalleTratamiento_listarTodosRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webapplication.odontosys.edu.pucp.pe/DetalleTratamientoWA/detalleTratamien" +
            "to_listarPorCitaRequest", ReplyAction="http://webapplication.odontosys.edu.pucp.pe/DetalleTratamientoWA/detalleTratamien" +
            "to_listarPorCitaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        OdontoSysWebApplication.DetalleTratamientoWS.detalleTratamiento_listarPorCitaResponse detalleTratamiento_listarPorCita(OdontoSysWebApplication.DetalleTratamientoWS.detalleTratamiento_listarPorCitaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webapplication.odontosys.edu.pucp.pe/DetalleTratamientoWA/detalleTratamien" +
            "to_listarPorCitaRequest", ReplyAction="http://webapplication.odontosys.edu.pucp.pe/DetalleTratamientoWA/detalleTratamien" +
            "to_listarPorCitaResponse")]
        System.Threading.Tasks.Task<OdontoSysWebApplication.DetalleTratamientoWS.detalleTratamiento_listarPorCitaResponse> detalleTratamiento_listarPorCitaAsync(OdontoSysWebApplication.DetalleTratamientoWS.detalleTratamiento_listarPorCitaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webapplication.odontosys.edu.pucp.pe/DetalleTratamientoWA/detalleTratamien" +
            "to_modificarRequest", ReplyAction="http://webapplication.odontosys.edu.pucp.pe/DetalleTratamientoWA/detalleTratamien" +
            "to_modificarResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        OdontoSysWebApplication.DetalleTratamientoWS.detalleTratamiento_modificarResponse detalleTratamiento_modificar(OdontoSysWebApplication.DetalleTratamientoWS.detalleTratamiento_modificarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webapplication.odontosys.edu.pucp.pe/DetalleTratamientoWA/detalleTratamien" +
            "to_modificarRequest", ReplyAction="http://webapplication.odontosys.edu.pucp.pe/DetalleTratamientoWA/detalleTratamien" +
            "to_modificarResponse")]
        System.Threading.Tasks.Task<OdontoSysWebApplication.DetalleTratamientoWS.detalleTratamiento_modificarResponse> detalleTratamiento_modificarAsync(OdontoSysWebApplication.DetalleTratamientoWS.detalleTratamiento_modificarRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webapplication.odontosys.edu.pucp.pe/DetalleTratamientoWA/detalleTratamien" +
            "to_eliminarRequest", ReplyAction="http://webapplication.odontosys.edu.pucp.pe/DetalleTratamientoWA/detalleTratamien" +
            "to_eliminarResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        OdontoSysWebApplication.DetalleTratamientoWS.detalleTratamiento_eliminarResponse detalleTratamiento_eliminar(OdontoSysWebApplication.DetalleTratamientoWS.detalleTratamiento_eliminarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webapplication.odontosys.edu.pucp.pe/DetalleTratamientoWA/detalleTratamien" +
            "to_eliminarRequest", ReplyAction="http://webapplication.odontosys.edu.pucp.pe/DetalleTratamientoWA/detalleTratamien" +
            "to_eliminarResponse")]
        System.Threading.Tasks.Task<OdontoSysWebApplication.DetalleTratamientoWS.detalleTratamiento_eliminarResponse> detalleTratamiento_eliminarAsync(OdontoSysWebApplication.DetalleTratamientoWS.detalleTratamiento_eliminarRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webapplication.odontosys.edu.pucp.pe/DetalleTratamientoWA/detalleTratamien" +
            "to_obtenerPorIdRequest", ReplyAction="http://webapplication.odontosys.edu.pucp.pe/DetalleTratamientoWA/detalleTratamien" +
            "to_obtenerPorIdResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        OdontoSysWebApplication.DetalleTratamientoWS.detalleTratamiento_obtenerPorIdResponse detalleTratamiento_obtenerPorId(OdontoSysWebApplication.DetalleTratamientoWS.detalleTratamiento_obtenerPorIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webapplication.odontosys.edu.pucp.pe/DetalleTratamientoWA/detalleTratamien" +
            "to_obtenerPorIdRequest", ReplyAction="http://webapplication.odontosys.edu.pucp.pe/DetalleTratamientoWA/detalleTratamien" +
            "to_obtenerPorIdResponse")]
        System.Threading.Tasks.Task<OdontoSysWebApplication.DetalleTratamientoWS.detalleTratamiento_obtenerPorIdResponse> detalleTratamiento_obtenerPorIdAsync(OdontoSysWebApplication.DetalleTratamientoWS.detalleTratamiento_obtenerPorIdRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webapplication.odontosys.edu.pucp.pe/DetalleTratamientoWA/detalleTratamien" +
            "to_actualizarSubtotalRequest", ReplyAction="http://webapplication.odontosys.edu.pucp.pe/DetalleTratamientoWA/detalleTratamien" +
            "to_actualizarSubtotalResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        OdontoSysWebApplication.DetalleTratamientoWS.detalleTratamiento_actualizarSubtotalResponse detalleTratamiento_actualizarSubtotal(OdontoSysWebApplication.DetalleTratamientoWS.detalleTratamiento_actualizarSubtotalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webapplication.odontosys.edu.pucp.pe/DetalleTratamientoWA/detalleTratamien" +
            "to_actualizarSubtotalRequest", ReplyAction="http://webapplication.odontosys.edu.pucp.pe/DetalleTratamientoWA/detalleTratamien" +
            "to_actualizarSubtotalResponse")]
        System.Threading.Tasks.Task<OdontoSysWebApplication.DetalleTratamientoWS.detalleTratamiento_actualizarSubtotalResponse> detalleTratamiento_actualizarSubtotalAsync(OdontoSysWebApplication.DetalleTratamientoWS.detalleTratamiento_actualizarSubtotalRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webapplication.odontosys.edu.pucp.pe/")]
    public partial class detalleTratamiento : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int cantidadField;
        
        private bool cantidadFieldSpecified;
        
        private int idCitaField;
        
        private bool idCitaFieldSpecified;
        
        private double subtotalField;
        
        private tratamiento tratamientoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int cantidad {
            get {
                return this.cantidadField;
            }
            set {
                this.cantidadField = value;
                this.RaisePropertyChanged("cantidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cantidadSpecified {
            get {
                return this.cantidadFieldSpecified;
            }
            set {
                this.cantidadFieldSpecified = value;
                this.RaisePropertyChanged("cantidadSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int idCita {
            get {
                return this.idCitaField;
            }
            set {
                this.idCitaField = value;
                this.RaisePropertyChanged("idCita");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idCitaSpecified {
            get {
                return this.idCitaFieldSpecified;
            }
            set {
                this.idCitaFieldSpecified = value;
                this.RaisePropertyChanged("idCitaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public double subtotal {
            get {
                return this.subtotalField;
            }
            set {
                this.subtotalField = value;
                this.RaisePropertyChanged("subtotal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public tratamiento tratamiento {
            get {
                return this.tratamientoField;
            }
            set {
                this.tratamientoField = value;
                this.RaisePropertyChanged("tratamiento");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webapplication.odontosys.edu.pucp.pe/")]
    public partial class tratamiento : object, System.ComponentModel.INotifyPropertyChanged {
        
        private double costoField;
        
        private string descripcionField;
        
        private especialidad especialidadField;
        
        private int idTratamientoField;
        
        private bool idTratamientoFieldSpecified;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public double costo {
            get {
                return this.costoField;
            }
            set {
                this.costoField = value;
                this.RaisePropertyChanged("costo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public especialidad especialidad {
            get {
                return this.especialidadField;
            }
            set {
                this.especialidadField = value;
                this.RaisePropertyChanged("especialidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int idTratamiento {
            get {
                return this.idTratamientoField;
            }
            set {
                this.idTratamientoField = value;
                this.RaisePropertyChanged("idTratamiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idTratamientoSpecified {
            get {
                return this.idTratamientoFieldSpecified;
            }
            set {
                this.idTratamientoFieldSpecified = value;
                this.RaisePropertyChanged("idTratamientoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webapplication.odontosys.edu.pucp.pe/")]
    public partial class especialidad : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idEspecialidadField;
        
        private bool idEspecialidadFieldSpecified;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int idEspecialidad {
            get {
                return this.idEspecialidadField;
            }
            set {
                this.idEspecialidadField = value;
                this.RaisePropertyChanged("idEspecialidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idEspecialidadSpecified {
            get {
                return this.idEspecialidadFieldSpecified;
            }
            set {
                this.idEspecialidadFieldSpecified = value;
                this.RaisePropertyChanged("idEspecialidadSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webapplication.odontosys.edu.pucp.pe/")]
    public partial class valoracion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int calicicacionField;
        
        private bool calicicacionFieldSpecified;
        
        private string comentarioField;
        
        private string fechaCalificacionField;
        
        private int idValoracionField;
        
        private bool idValoracionFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int calicicacion {
            get {
                return this.calicicacionField;
            }
            set {
                this.calicicacionField = value;
                this.RaisePropertyChanged("calicicacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool calicicacionSpecified {
            get {
                return this.calicicacionFieldSpecified;
            }
            set {
                this.calicicacionFieldSpecified = value;
                this.RaisePropertyChanged("calicicacionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string comentario {
            get {
                return this.comentarioField;
            }
            set {
                this.comentarioField = value;
                this.RaisePropertyChanged("comentario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string fechaCalificacion {
            get {
                return this.fechaCalificacionField;
            }
            set {
                this.fechaCalificacionField = value;
                this.RaisePropertyChanged("fechaCalificacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int idValoracion {
            get {
                return this.idValoracionField;
            }
            set {
                this.idValoracionField = value;
                this.RaisePropertyChanged("idValoracion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idValoracionSpecified {
            get {
                return this.idValoracionFieldSpecified;
            }
            set {
                this.idValoracionFieldSpecified = value;
                this.RaisePropertyChanged("idValoracionSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webapplication.odontosys.edu.pucp.pe/")]
    public partial class turno : object, System.ComponentModel.INotifyPropertyChanged {
        
        private diaSemana diaSemanaField;
        
        private bool diaSemanaFieldSpecified;
        
        private string horaFinField;
        
        private string horaInicioField;
        
        private int idTurnoField;
        
        private bool idTurnoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public diaSemana diaSemana {
            get {
                return this.diaSemanaField;
            }
            set {
                this.diaSemanaField = value;
                this.RaisePropertyChanged("diaSemana");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool diaSemanaSpecified {
            get {
                return this.diaSemanaFieldSpecified;
            }
            set {
                this.diaSemanaFieldSpecified = value;
                this.RaisePropertyChanged("diaSemanaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string horaFin {
            get {
                return this.horaFinField;
            }
            set {
                this.horaFinField = value;
                this.RaisePropertyChanged("horaFin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string horaInicio {
            get {
                return this.horaInicioField;
            }
            set {
                this.horaInicioField = value;
                this.RaisePropertyChanged("horaInicio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int idTurno {
            get {
                return this.idTurnoField;
            }
            set {
                this.idTurnoField = value;
                this.RaisePropertyChanged("idTurno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idTurnoSpecified {
            get {
                return this.idTurnoFieldSpecified;
            }
            set {
                this.idTurnoFieldSpecified = value;
                this.RaisePropertyChanged("idTurnoSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webapplication.odontosys.edu.pucp.pe/")]
    public enum diaSemana {
        
        /// <remarks/>
        MONDAY,
        
        /// <remarks/>
        TUESDAY,
        
        /// <remarks/>
        WEDNESDAY,
        
        /// <remarks/>
        THURSDAY,
        
        /// <remarks/>
        FRIDAY,
        
        /// <remarks/>
        SATURDAY,
        
        /// <remarks/>
        SUNDAY,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webapplication.odontosys.edu.pucp.pe/")]
    public partial class sala : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idSalaField;
        
        private bool idSalaFieldSpecified;
        
        private string numeroField;
        
        private int pisoField;
        
        private bool pisoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int idSala {
            get {
                return this.idSalaField;
            }
            set {
                this.idSalaField = value;
                this.RaisePropertyChanged("idSala");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSalaSpecified {
            get {
                return this.idSalaFieldSpecified;
            }
            set {
                this.idSalaFieldSpecified = value;
                this.RaisePropertyChanged("idSalaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
                this.RaisePropertyChanged("numero");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int piso {
            get {
                return this.pisoField;
            }
            set {
                this.pisoField = value;
                this.RaisePropertyChanged("piso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pisoSpecified {
            get {
                return this.pisoFieldSpecified;
            }
            set {
                this.pisoFieldSpecified = value;
                this.RaisePropertyChanged("pisoSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webapplication.odontosys.edu.pucp.pe/")]
    public partial class tipoDocumento : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idTipoDocumentoField;
        
        private bool idTipoDocumentoFieldSpecified;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int idTipoDocumento {
            get {
                return this.idTipoDocumentoField;
            }
            set {
                this.idTipoDocumentoField = value;
                this.RaisePropertyChanged("idTipoDocumento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idTipoDocumentoSpecified {
            get {
                return this.idTipoDocumentoFieldSpecified;
            }
            set {
                this.idTipoDocumentoFieldSpecified = value;
                this.RaisePropertyChanged("idTipoDocumentoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(recepcionista))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(paciente))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(odontologo))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webapplication.odontosys.edu.pucp.pe/")]
    public abstract partial class persona : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string apellidosField;
        
        private string contrasenhaField;
        
        private string correoField;
        
        private string nombreField;
        
        private string nombreUsuarioField;
        
        private string numeroDocumentoField;
        
        private string telefonoField;
        
        private tipoDocumento tipoDocumentoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string apellidos {
            get {
                return this.apellidosField;
            }
            set {
                this.apellidosField = value;
                this.RaisePropertyChanged("apellidos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string contrasenha {
            get {
                return this.contrasenhaField;
            }
            set {
                this.contrasenhaField = value;
                this.RaisePropertyChanged("contrasenha");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string correo {
            get {
                return this.correoField;
            }
            set {
                this.correoField = value;
                this.RaisePropertyChanged("correo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string nombreUsuario {
            get {
                return this.nombreUsuarioField;
            }
            set {
                this.nombreUsuarioField = value;
                this.RaisePropertyChanged("nombreUsuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string numeroDocumento {
            get {
                return this.numeroDocumentoField;
            }
            set {
                this.numeroDocumentoField = value;
                this.RaisePropertyChanged("numeroDocumento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("telefono");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public tipoDocumento tipoDocumento {
            get {
                return this.tipoDocumentoField;
            }
            set {
                this.tipoDocumentoField = value;
                this.RaisePropertyChanged("tipoDocumento");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webapplication.odontosys.edu.pucp.pe/")]
    public partial class recepcionista : persona {
        
        private cita[] citasField;
        
        private int idRecepcionistaField;
        
        private bool idRecepcionistaFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("citas", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public cita[] citas {
            get {
                return this.citasField;
            }
            set {
                this.citasField = value;
                this.RaisePropertyChanged("citas");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int idRecepcionista {
            get {
                return this.idRecepcionistaField;
            }
            set {
                this.idRecepcionistaField = value;
                this.RaisePropertyChanged("idRecepcionista");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idRecepcionistaSpecified {
            get {
                return this.idRecepcionistaFieldSpecified;
            }
            set {
                this.idRecepcionistaFieldSpecified = value;
                this.RaisePropertyChanged("idRecepcionistaSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webapplication.odontosys.edu.pucp.pe/")]
    public partial class cita : object, System.ComponentModel.INotifyPropertyChanged {
        
        private comprobante comprobanteField;
        
        private estadoCita estadoField;
        
        private bool estadoFieldSpecified;
        
        private string fechaField;
        
        private string horaInicioField;
        
        private int idCitaField;
        
        private bool idCitaFieldSpecified;
        
        private odontologo odontologoField;
        
        private paciente pacienteField;
        
        private recepcionista recepcionistaField;
        
        private detalleTratamiento[] tratamientosField;
        
        private valoracion valoracionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public comprobante comprobante {
            get {
                return this.comprobanteField;
            }
            set {
                this.comprobanteField = value;
                this.RaisePropertyChanged("comprobante");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public estadoCita estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool estadoSpecified {
            get {
                return this.estadoFieldSpecified;
            }
            set {
                this.estadoFieldSpecified = value;
                this.RaisePropertyChanged("estadoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
                this.RaisePropertyChanged("fecha");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string horaInicio {
            get {
                return this.horaInicioField;
            }
            set {
                this.horaInicioField = value;
                this.RaisePropertyChanged("horaInicio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int idCita {
            get {
                return this.idCitaField;
            }
            set {
                this.idCitaField = value;
                this.RaisePropertyChanged("idCita");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idCitaSpecified {
            get {
                return this.idCitaFieldSpecified;
            }
            set {
                this.idCitaFieldSpecified = value;
                this.RaisePropertyChanged("idCitaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public odontologo odontologo {
            get {
                return this.odontologoField;
            }
            set {
                this.odontologoField = value;
                this.RaisePropertyChanged("odontologo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public paciente paciente {
            get {
                return this.pacienteField;
            }
            set {
                this.pacienteField = value;
                this.RaisePropertyChanged("paciente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public recepcionista recepcionista {
            get {
                return this.recepcionistaField;
            }
            set {
                this.recepcionistaField = value;
                this.RaisePropertyChanged("recepcionista");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("tratamientos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=8)]
        public detalleTratamiento[] tratamientos {
            get {
                return this.tratamientosField;
            }
            set {
                this.tratamientosField = value;
                this.RaisePropertyChanged("tratamientos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public valoracion valoracion {
            get {
                return this.valoracionField;
            }
            set {
                this.valoracionField = value;
                this.RaisePropertyChanged("valoracion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webapplication.odontosys.edu.pucp.pe/")]
    public partial class comprobante : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fechaEmisionField;
        
        private string horaEmisionField;
        
        private int idComprobanteField;
        
        private bool idComprobanteFieldSpecified;
        
        private metodoPago metodoDePagoField;
        
        private double totalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string fechaEmision {
            get {
                return this.fechaEmisionField;
            }
            set {
                this.fechaEmisionField = value;
                this.RaisePropertyChanged("fechaEmision");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string horaEmision {
            get {
                return this.horaEmisionField;
            }
            set {
                this.horaEmisionField = value;
                this.RaisePropertyChanged("horaEmision");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idComprobante {
            get {
                return this.idComprobanteField;
            }
            set {
                this.idComprobanteField = value;
                this.RaisePropertyChanged("idComprobante");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idComprobanteSpecified {
            get {
                return this.idComprobanteFieldSpecified;
            }
            set {
                this.idComprobanteFieldSpecified = value;
                this.RaisePropertyChanged("idComprobanteSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public metodoPago metodoDePago {
            get {
                return this.metodoDePagoField;
            }
            set {
                this.metodoDePagoField = value;
                this.RaisePropertyChanged("metodoDePago");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public double total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
                this.RaisePropertyChanged("total");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webapplication.odontosys.edu.pucp.pe/")]
    public partial class metodoPago : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idMetodoPagoField;
        
        private bool idMetodoPagoFieldSpecified;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int idMetodoPago {
            get {
                return this.idMetodoPagoField;
            }
            set {
                this.idMetodoPagoField = value;
                this.RaisePropertyChanged("idMetodoPago");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idMetodoPagoSpecified {
            get {
                return this.idMetodoPagoFieldSpecified;
            }
            set {
                this.idMetodoPagoFieldSpecified = value;
                this.RaisePropertyChanged("idMetodoPagoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webapplication.odontosys.edu.pucp.pe/")]
    public enum estadoCita {
        
        /// <remarks/>
        RESERVADA,
        
        /// <remarks/>
        ATENDIDA,
        
        /// <remarks/>
        CANCELADA,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webapplication.odontosys.edu.pucp.pe/")]
    public partial class odontologo : persona {
        
        private cita[] citasField;
        
        private sala consultorioField;
        
        private especialidad especialidadField;
        
        private int idOdontologoField;
        
        private bool idOdontologoFieldSpecified;
        
        private double puntuacionPromedioField;
        
        private turno[] turnosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("citas", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public cita[] citas {
            get {
                return this.citasField;
            }
            set {
                this.citasField = value;
                this.RaisePropertyChanged("citas");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public sala consultorio {
            get {
                return this.consultorioField;
            }
            set {
                this.consultorioField = value;
                this.RaisePropertyChanged("consultorio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public especialidad especialidad {
            get {
                return this.especialidadField;
            }
            set {
                this.especialidadField = value;
                this.RaisePropertyChanged("especialidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int idOdontologo {
            get {
                return this.idOdontologoField;
            }
            set {
                this.idOdontologoField = value;
                this.RaisePropertyChanged("idOdontologo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idOdontologoSpecified {
            get {
                return this.idOdontologoFieldSpecified;
            }
            set {
                this.idOdontologoFieldSpecified = value;
                this.RaisePropertyChanged("idOdontologoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public double puntuacionPromedio {
            get {
                return this.puntuacionPromedioField;
            }
            set {
                this.puntuacionPromedioField = value;
                this.RaisePropertyChanged("puntuacionPromedio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("turnos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public turno[] turnos {
            get {
                return this.turnosField;
            }
            set {
                this.turnosField = value;
                this.RaisePropertyChanged("turnos");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webapplication.odontosys.edu.pucp.pe/")]
    public partial class paciente : persona {
        
        private cita[] citasField;
        
        private int idPacienteField;
        
        private bool idPacienteFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("citas", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public cita[] citas {
            get {
                return this.citasField;
            }
            set {
                this.citasField = value;
                this.RaisePropertyChanged("citas");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int idPaciente {
            get {
                return this.idPacienteField;
            }
            set {
                this.idPacienteField = value;
                this.RaisePropertyChanged("idPaciente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idPacienteSpecified {
            get {
                return this.idPacienteFieldSpecified;
            }
            set {
                this.idPacienteFieldSpecified = value;
                this.RaisePropertyChanged("idPacienteSpecified");
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="detalleTratamiento_insertar", WrapperNamespace="http://webapplication.odontosys.edu.pucp.pe/", IsWrapped=true)]
    public partial class detalleTratamiento_insertarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webapplication.odontosys.edu.pucp.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public OdontoSysWebApplication.DetalleTratamientoWS.detalleTratamiento detalleTratamiento;
        
        public detalleTratamiento_insertarRequest() {
        }
        
        public detalleTratamiento_insertarRequest(OdontoSysWebApplication.DetalleTratamientoWS.detalleTratamiento detalleTratamiento) {
            this.detalleTratamiento = detalleTratamiento;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="detalleTratamiento_insertarResponse", WrapperNamespace="http://webapplication.odontosys.edu.pucp.pe/", IsWrapped=true)]
    public partial class detalleTratamiento_insertarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webapplication.odontosys.edu.pucp.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public detalleTratamiento_insertarResponse() {
        }
        
        public detalleTratamiento_insertarResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="detalleTratamiento_listarTodos", WrapperNamespace="http://webapplication.odontosys.edu.pucp.pe/", IsWrapped=true)]
    public partial class detalleTratamiento_listarTodosRequest {
        
        public detalleTratamiento_listarTodosRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="detalleTratamiento_listarTodosResponse", WrapperNamespace="http://webapplication.odontosys.edu.pucp.pe/", IsWrapped=true)]
    public partial class detalleTratamiento_listarTodosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webapplication.odontosys.edu.pucp.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public OdontoSysWebApplication.DetalleTratamientoWS.detalleTratamiento[] @return;
        
        public detalleTratamiento_listarTodosResponse() {
        }
        
        public detalleTratamiento_listarTodosResponse(OdontoSysWebApplication.DetalleTratamientoWS.detalleTratamiento[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="detalleTratamiento_listarPorCita", WrapperNamespace="http://webapplication.odontosys.edu.pucp.pe/", IsWrapped=true)]
    public partial class detalleTratamiento_listarPorCitaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webapplication.odontosys.edu.pucp.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public OdontoSysWebApplication.DetalleTratamientoWS.cita cita;
        
        public detalleTratamiento_listarPorCitaRequest() {
        }
        
        public detalleTratamiento_listarPorCitaRequest(OdontoSysWebApplication.DetalleTratamientoWS.cita cita) {
            this.cita = cita;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="detalleTratamiento_listarPorCitaResponse", WrapperNamespace="http://webapplication.odontosys.edu.pucp.pe/", IsWrapped=true)]
    public partial class detalleTratamiento_listarPorCitaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webapplication.odontosys.edu.pucp.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public OdontoSysWebApplication.DetalleTratamientoWS.detalleTratamiento[] @return;
        
        public detalleTratamiento_listarPorCitaResponse() {
        }
        
        public detalleTratamiento_listarPorCitaResponse(OdontoSysWebApplication.DetalleTratamientoWS.detalleTratamiento[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="detalleTratamiento_modificar", WrapperNamespace="http://webapplication.odontosys.edu.pucp.pe/", IsWrapped=true)]
    public partial class detalleTratamiento_modificarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webapplication.odontosys.edu.pucp.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public OdontoSysWebApplication.DetalleTratamientoWS.detalleTratamiento detalleTratamiento;
        
        public detalleTratamiento_modificarRequest() {
        }
        
        public detalleTratamiento_modificarRequest(OdontoSysWebApplication.DetalleTratamientoWS.detalleTratamiento detalleTratamiento) {
            this.detalleTratamiento = detalleTratamiento;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="detalleTratamiento_modificarResponse", WrapperNamespace="http://webapplication.odontosys.edu.pucp.pe/", IsWrapped=true)]
    public partial class detalleTratamiento_modificarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webapplication.odontosys.edu.pucp.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public detalleTratamiento_modificarResponse() {
        }
        
        public detalleTratamiento_modificarResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="detalleTratamiento_eliminar", WrapperNamespace="http://webapplication.odontosys.edu.pucp.pe/", IsWrapped=true)]
    public partial class detalleTratamiento_eliminarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webapplication.odontosys.edu.pucp.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public OdontoSysWebApplication.DetalleTratamientoWS.detalleTratamiento detalleTratamiento;
        
        public detalleTratamiento_eliminarRequest() {
        }
        
        public detalleTratamiento_eliminarRequest(OdontoSysWebApplication.DetalleTratamientoWS.detalleTratamiento detalleTratamiento) {
            this.detalleTratamiento = detalleTratamiento;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="detalleTratamiento_eliminarResponse", WrapperNamespace="http://webapplication.odontosys.edu.pucp.pe/", IsWrapped=true)]
    public partial class detalleTratamiento_eliminarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webapplication.odontosys.edu.pucp.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public detalleTratamiento_eliminarResponse() {
        }
        
        public detalleTratamiento_eliminarResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="detalleTratamiento_obtenerPorId", WrapperNamespace="http://webapplication.odontosys.edu.pucp.pe/", IsWrapped=true)]
    public partial class detalleTratamiento_obtenerPorIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webapplication.odontosys.edu.pucp.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public detalleTratamiento_obtenerPorIdRequest() {
        }
        
        public detalleTratamiento_obtenerPorIdRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="detalleTratamiento_obtenerPorIdResponse", WrapperNamespace="http://webapplication.odontosys.edu.pucp.pe/", IsWrapped=true)]
    public partial class detalleTratamiento_obtenerPorIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webapplication.odontosys.edu.pucp.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public OdontoSysWebApplication.DetalleTratamientoWS.detalleTratamiento @return;
        
        public detalleTratamiento_obtenerPorIdResponse() {
        }
        
        public detalleTratamiento_obtenerPorIdResponse(OdontoSysWebApplication.DetalleTratamientoWS.detalleTratamiento @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="detalleTratamiento_actualizarSubtotal", WrapperNamespace="http://webapplication.odontosys.edu.pucp.pe/", IsWrapped=true)]
    public partial class detalleTratamiento_actualizarSubtotalRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webapplication.odontosys.edu.pucp.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public OdontoSysWebApplication.DetalleTratamientoWS.cita cita;
        
        public detalleTratamiento_actualizarSubtotalRequest() {
        }
        
        public detalleTratamiento_actualizarSubtotalRequest(OdontoSysWebApplication.DetalleTratamientoWS.cita cita) {
            this.cita = cita;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="detalleTratamiento_actualizarSubtotalResponse", WrapperNamespace="http://webapplication.odontosys.edu.pucp.pe/", IsWrapped=true)]
    public partial class detalleTratamiento_actualizarSubtotalResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webapplication.odontosys.edu.pucp.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public detalleTratamiento_actualizarSubtotalResponse() {
        }
        
        public detalleTratamiento_actualizarSubtotalResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DetalleTratamientoWAChannel : OdontoSysWebApplication.DetalleTratamientoWS.DetalleTratamientoWA, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DetalleTratamientoWAClient : System.ServiceModel.ClientBase<OdontoSysWebApplication.DetalleTratamientoWS.DetalleTratamientoWA>, OdontoSysWebApplication.DetalleTratamientoWS.DetalleTratamientoWA {
        
        public DetalleTratamientoWAClient() {
        }
        
        public DetalleTratamientoWAClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DetalleTratamientoWAClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DetalleTratamientoWAClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DetalleTratamientoWAClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OdontoSysWebApplication.DetalleTratamientoWS.detalleTratamiento_insertarResponse OdontoSysWebApplication.DetalleTratamientoWS.DetalleTratamientoWA.detalleTratamiento_insertar(OdontoSysWebApplication.DetalleTratamientoWS.detalleTratamiento_insertarRequest request) {
            return base.Channel.detalleTratamiento_insertar(request);
        }
        
        public int detalleTratamiento_insertar(OdontoSysWebApplication.DetalleTratamientoWS.detalleTratamiento detalleTratamiento) {
            OdontoSysWebApplication.DetalleTratamientoWS.detalleTratamiento_insertarRequest inValue = new OdontoSysWebApplication.DetalleTratamientoWS.detalleTratamiento_insertarRequest();
            inValue.detalleTratamiento = detalleTratamiento;
            OdontoSysWebApplication.DetalleTratamientoWS.detalleTratamiento_insertarResponse retVal = ((OdontoSysWebApplication.DetalleTratamientoWS.DetalleTratamientoWA)(this)).detalleTratamiento_insertar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OdontoSysWebApplication.DetalleTratamientoWS.detalleTratamiento_insertarResponse> OdontoSysWebApplication.DetalleTratamientoWS.DetalleTratamientoWA.detalleTratamiento_insertarAsync(OdontoSysWebApplication.DetalleTratamientoWS.detalleTratamiento_insertarRequest request) {
            return base.Channel.detalleTratamiento_insertarAsync(request);
        }
        
        public System.Threading.Tasks.Task<OdontoSysWebApplication.DetalleTratamientoWS.detalleTratamiento_insertarResponse> detalleTratamiento_insertarAsync(OdontoSysWebApplication.DetalleTratamientoWS.detalleTratamiento detalleTratamiento) {
            OdontoSysWebApplication.DetalleTratamientoWS.detalleTratamiento_insertarRequest inValue = new OdontoSysWebApplication.DetalleTratamientoWS.detalleTratamiento_insertarRequest();
            inValue.detalleTratamiento = detalleTratamiento;
            return ((OdontoSysWebApplication.DetalleTratamientoWS.DetalleTratamientoWA)(this)).detalleTratamiento_insertarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OdontoSysWebApplication.DetalleTratamientoWS.detalleTratamiento_listarTodosResponse OdontoSysWebApplication.DetalleTratamientoWS.DetalleTratamientoWA.detalleTratamiento_listarTodos(OdontoSysWebApplication.DetalleTratamientoWS.detalleTratamiento_listarTodosRequest request) {
            return base.Channel.detalleTratamiento_listarTodos(request);
        }
        
        public OdontoSysWebApplication.DetalleTratamientoWS.detalleTratamiento[] detalleTratamiento_listarTodos() {
            OdontoSysWebApplication.DetalleTratamientoWS.detalleTratamiento_listarTodosRequest inValue = new OdontoSysWebApplication.DetalleTratamientoWS.detalleTratamiento_listarTodosRequest();
            OdontoSysWebApplication.DetalleTratamientoWS.detalleTratamiento_listarTodosResponse retVal = ((OdontoSysWebApplication.DetalleTratamientoWS.DetalleTratamientoWA)(this)).detalleTratamiento_listarTodos(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OdontoSysWebApplication.DetalleTratamientoWS.detalleTratamiento_listarTodosResponse> OdontoSysWebApplication.DetalleTratamientoWS.DetalleTratamientoWA.detalleTratamiento_listarTodosAsync(OdontoSysWebApplication.DetalleTratamientoWS.detalleTratamiento_listarTodosRequest request) {
            return base.Channel.detalleTratamiento_listarTodosAsync(request);
        }
        
        public System.Threading.Tasks.Task<OdontoSysWebApplication.DetalleTratamientoWS.detalleTratamiento_listarTodosResponse> detalleTratamiento_listarTodosAsync() {
            OdontoSysWebApplication.DetalleTratamientoWS.detalleTratamiento_listarTodosRequest inValue = new OdontoSysWebApplication.DetalleTratamientoWS.detalleTratamiento_listarTodosRequest();
            return ((OdontoSysWebApplication.DetalleTratamientoWS.DetalleTratamientoWA)(this)).detalleTratamiento_listarTodosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OdontoSysWebApplication.DetalleTratamientoWS.detalleTratamiento_listarPorCitaResponse OdontoSysWebApplication.DetalleTratamientoWS.DetalleTratamientoWA.detalleTratamiento_listarPorCita(OdontoSysWebApplication.DetalleTratamientoWS.detalleTratamiento_listarPorCitaRequest request) {
            return base.Channel.detalleTratamiento_listarPorCita(request);
        }
        
        public OdontoSysWebApplication.DetalleTratamientoWS.detalleTratamiento[] detalleTratamiento_listarPorCita(OdontoSysWebApplication.DetalleTratamientoWS.cita cita) {
            OdontoSysWebApplication.DetalleTratamientoWS.detalleTratamiento_listarPorCitaRequest inValue = new OdontoSysWebApplication.DetalleTratamientoWS.detalleTratamiento_listarPorCitaRequest();
            inValue.cita = cita;
            OdontoSysWebApplication.DetalleTratamientoWS.detalleTratamiento_listarPorCitaResponse retVal = ((OdontoSysWebApplication.DetalleTratamientoWS.DetalleTratamientoWA)(this)).detalleTratamiento_listarPorCita(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OdontoSysWebApplication.DetalleTratamientoWS.detalleTratamiento_listarPorCitaResponse> OdontoSysWebApplication.DetalleTratamientoWS.DetalleTratamientoWA.detalleTratamiento_listarPorCitaAsync(OdontoSysWebApplication.DetalleTratamientoWS.detalleTratamiento_listarPorCitaRequest request) {
            return base.Channel.detalleTratamiento_listarPorCitaAsync(request);
        }
        
        public System.Threading.Tasks.Task<OdontoSysWebApplication.DetalleTratamientoWS.detalleTratamiento_listarPorCitaResponse> detalleTratamiento_listarPorCitaAsync(OdontoSysWebApplication.DetalleTratamientoWS.cita cita) {
            OdontoSysWebApplication.DetalleTratamientoWS.detalleTratamiento_listarPorCitaRequest inValue = new OdontoSysWebApplication.DetalleTratamientoWS.detalleTratamiento_listarPorCitaRequest();
            inValue.cita = cita;
            return ((OdontoSysWebApplication.DetalleTratamientoWS.DetalleTratamientoWA)(this)).detalleTratamiento_listarPorCitaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OdontoSysWebApplication.DetalleTratamientoWS.detalleTratamiento_modificarResponse OdontoSysWebApplication.DetalleTratamientoWS.DetalleTratamientoWA.detalleTratamiento_modificar(OdontoSysWebApplication.DetalleTratamientoWS.detalleTratamiento_modificarRequest request) {
            return base.Channel.detalleTratamiento_modificar(request);
        }
        
        public int detalleTratamiento_modificar(OdontoSysWebApplication.DetalleTratamientoWS.detalleTratamiento detalleTratamiento) {
            OdontoSysWebApplication.DetalleTratamientoWS.detalleTratamiento_modificarRequest inValue = new OdontoSysWebApplication.DetalleTratamientoWS.detalleTratamiento_modificarRequest();
            inValue.detalleTratamiento = detalleTratamiento;
            OdontoSysWebApplication.DetalleTratamientoWS.detalleTratamiento_modificarResponse retVal = ((OdontoSysWebApplication.DetalleTratamientoWS.DetalleTratamientoWA)(this)).detalleTratamiento_modificar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OdontoSysWebApplication.DetalleTratamientoWS.detalleTratamiento_modificarResponse> OdontoSysWebApplication.DetalleTratamientoWS.DetalleTratamientoWA.detalleTratamiento_modificarAsync(OdontoSysWebApplication.DetalleTratamientoWS.detalleTratamiento_modificarRequest request) {
            return base.Channel.detalleTratamiento_modificarAsync(request);
        }
        
        public System.Threading.Tasks.Task<OdontoSysWebApplication.DetalleTratamientoWS.detalleTratamiento_modificarResponse> detalleTratamiento_modificarAsync(OdontoSysWebApplication.DetalleTratamientoWS.detalleTratamiento detalleTratamiento) {
            OdontoSysWebApplication.DetalleTratamientoWS.detalleTratamiento_modificarRequest inValue = new OdontoSysWebApplication.DetalleTratamientoWS.detalleTratamiento_modificarRequest();
            inValue.detalleTratamiento = detalleTratamiento;
            return ((OdontoSysWebApplication.DetalleTratamientoWS.DetalleTratamientoWA)(this)).detalleTratamiento_modificarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OdontoSysWebApplication.DetalleTratamientoWS.detalleTratamiento_eliminarResponse OdontoSysWebApplication.DetalleTratamientoWS.DetalleTratamientoWA.detalleTratamiento_eliminar(OdontoSysWebApplication.DetalleTratamientoWS.detalleTratamiento_eliminarRequest request) {
            return base.Channel.detalleTratamiento_eliminar(request);
        }
        
        public int detalleTratamiento_eliminar(OdontoSysWebApplication.DetalleTratamientoWS.detalleTratamiento detalleTratamiento) {
            OdontoSysWebApplication.DetalleTratamientoWS.detalleTratamiento_eliminarRequest inValue = new OdontoSysWebApplication.DetalleTratamientoWS.detalleTratamiento_eliminarRequest();
            inValue.detalleTratamiento = detalleTratamiento;
            OdontoSysWebApplication.DetalleTratamientoWS.detalleTratamiento_eliminarResponse retVal = ((OdontoSysWebApplication.DetalleTratamientoWS.DetalleTratamientoWA)(this)).detalleTratamiento_eliminar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OdontoSysWebApplication.DetalleTratamientoWS.detalleTratamiento_eliminarResponse> OdontoSysWebApplication.DetalleTratamientoWS.DetalleTratamientoWA.detalleTratamiento_eliminarAsync(OdontoSysWebApplication.DetalleTratamientoWS.detalleTratamiento_eliminarRequest request) {
            return base.Channel.detalleTratamiento_eliminarAsync(request);
        }
        
        public System.Threading.Tasks.Task<OdontoSysWebApplication.DetalleTratamientoWS.detalleTratamiento_eliminarResponse> detalleTratamiento_eliminarAsync(OdontoSysWebApplication.DetalleTratamientoWS.detalleTratamiento detalleTratamiento) {
            OdontoSysWebApplication.DetalleTratamientoWS.detalleTratamiento_eliminarRequest inValue = new OdontoSysWebApplication.DetalleTratamientoWS.detalleTratamiento_eliminarRequest();
            inValue.detalleTratamiento = detalleTratamiento;
            return ((OdontoSysWebApplication.DetalleTratamientoWS.DetalleTratamientoWA)(this)).detalleTratamiento_eliminarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OdontoSysWebApplication.DetalleTratamientoWS.detalleTratamiento_obtenerPorIdResponse OdontoSysWebApplication.DetalleTratamientoWS.DetalleTratamientoWA.detalleTratamiento_obtenerPorId(OdontoSysWebApplication.DetalleTratamientoWS.detalleTratamiento_obtenerPorIdRequest request) {
            return base.Channel.detalleTratamiento_obtenerPorId(request);
        }
        
        public OdontoSysWebApplication.DetalleTratamientoWS.detalleTratamiento detalleTratamiento_obtenerPorId(int id) {
            OdontoSysWebApplication.DetalleTratamientoWS.detalleTratamiento_obtenerPorIdRequest inValue = new OdontoSysWebApplication.DetalleTratamientoWS.detalleTratamiento_obtenerPorIdRequest();
            inValue.id = id;
            OdontoSysWebApplication.DetalleTratamientoWS.detalleTratamiento_obtenerPorIdResponse retVal = ((OdontoSysWebApplication.DetalleTratamientoWS.DetalleTratamientoWA)(this)).detalleTratamiento_obtenerPorId(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OdontoSysWebApplication.DetalleTratamientoWS.detalleTratamiento_obtenerPorIdResponse> OdontoSysWebApplication.DetalleTratamientoWS.DetalleTratamientoWA.detalleTratamiento_obtenerPorIdAsync(OdontoSysWebApplication.DetalleTratamientoWS.detalleTratamiento_obtenerPorIdRequest request) {
            return base.Channel.detalleTratamiento_obtenerPorIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<OdontoSysWebApplication.DetalleTratamientoWS.detalleTratamiento_obtenerPorIdResponse> detalleTratamiento_obtenerPorIdAsync(int id) {
            OdontoSysWebApplication.DetalleTratamientoWS.detalleTratamiento_obtenerPorIdRequest inValue = new OdontoSysWebApplication.DetalleTratamientoWS.detalleTratamiento_obtenerPorIdRequest();
            inValue.id = id;
            return ((OdontoSysWebApplication.DetalleTratamientoWS.DetalleTratamientoWA)(this)).detalleTratamiento_obtenerPorIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OdontoSysWebApplication.DetalleTratamientoWS.detalleTratamiento_actualizarSubtotalResponse OdontoSysWebApplication.DetalleTratamientoWS.DetalleTratamientoWA.detalleTratamiento_actualizarSubtotal(OdontoSysWebApplication.DetalleTratamientoWS.detalleTratamiento_actualizarSubtotalRequest request) {
            return base.Channel.detalleTratamiento_actualizarSubtotal(request);
        }
        
        public int detalleTratamiento_actualizarSubtotal(OdontoSysWebApplication.DetalleTratamientoWS.cita cita) {
            OdontoSysWebApplication.DetalleTratamientoWS.detalleTratamiento_actualizarSubtotalRequest inValue = new OdontoSysWebApplication.DetalleTratamientoWS.detalleTratamiento_actualizarSubtotalRequest();
            inValue.cita = cita;
            OdontoSysWebApplication.DetalleTratamientoWS.detalleTratamiento_actualizarSubtotalResponse retVal = ((OdontoSysWebApplication.DetalleTratamientoWS.DetalleTratamientoWA)(this)).detalleTratamiento_actualizarSubtotal(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OdontoSysWebApplication.DetalleTratamientoWS.detalleTratamiento_actualizarSubtotalResponse> OdontoSysWebApplication.DetalleTratamientoWS.DetalleTratamientoWA.detalleTratamiento_actualizarSubtotalAsync(OdontoSysWebApplication.DetalleTratamientoWS.detalleTratamiento_actualizarSubtotalRequest request) {
            return base.Channel.detalleTratamiento_actualizarSubtotalAsync(request);
        }
        
        public System.Threading.Tasks.Task<OdontoSysWebApplication.DetalleTratamientoWS.detalleTratamiento_actualizarSubtotalResponse> detalleTratamiento_actualizarSubtotalAsync(OdontoSysWebApplication.DetalleTratamientoWS.cita cita) {
            OdontoSysWebApplication.DetalleTratamientoWS.detalleTratamiento_actualizarSubtotalRequest inValue = new OdontoSysWebApplication.DetalleTratamientoWS.detalleTratamiento_actualizarSubtotalRequest();
            inValue.cita = cita;
            return ((OdontoSysWebApplication.DetalleTratamientoWS.DetalleTratamientoWA)(this)).detalleTratamiento_actualizarSubtotalAsync(inValue);
        }
    }
}
