//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OdontoSysBusiness.DetalleTratamientoWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webapplication.odontosys.edu.pucp.pe/", ConfigurationName="DetalleTratamientoWS.DetalleTratamientoWA")]
    public interface DetalleTratamientoWA {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webapplication.odontosys.edu.pucp.pe/DetalleTratamientoWA/detalleTratamien" +
            "to_actualizarSubtotalRequest", ReplyAction="http://webapplication.odontosys.edu.pucp.pe/DetalleTratamientoWA/detalleTratamien" +
            "to_actualizarSubtotalResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        OdontoSysBusiness.DetalleTratamientoWS.detalleTratamiento_actualizarSubtotalResponse detalleTratamiento_actualizarSubtotal(OdontoSysBusiness.DetalleTratamientoWS.detalleTratamiento_actualizarSubtotalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webapplication.odontosys.edu.pucp.pe/DetalleTratamientoWA/detalleTratamien" +
            "to_actualizarSubtotalRequest", ReplyAction="http://webapplication.odontosys.edu.pucp.pe/DetalleTratamientoWA/detalleTratamien" +
            "to_actualizarSubtotalResponse")]
        System.Threading.Tasks.Task<OdontoSysBusiness.DetalleTratamientoWS.detalleTratamiento_actualizarSubtotalResponse> detalleTratamiento_actualizarSubtotalAsync(OdontoSysBusiness.DetalleTratamientoWS.detalleTratamiento_actualizarSubtotalRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webapplication.odontosys.edu.pucp.pe/DetalleTratamientoWA/detalleTratamien" +
            "to_eliminarRequest", ReplyAction="http://webapplication.odontosys.edu.pucp.pe/DetalleTratamientoWA/detalleTratamien" +
            "to_eliminarResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        OdontoSysBusiness.DetalleTratamientoWS.detalleTratamiento_eliminarResponse detalleTratamiento_eliminar(OdontoSysBusiness.DetalleTratamientoWS.detalleTratamiento_eliminarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webapplication.odontosys.edu.pucp.pe/DetalleTratamientoWA/detalleTratamien" +
            "to_eliminarRequest", ReplyAction="http://webapplication.odontosys.edu.pucp.pe/DetalleTratamientoWA/detalleTratamien" +
            "to_eliminarResponse")]
        System.Threading.Tasks.Task<OdontoSysBusiness.DetalleTratamientoWS.detalleTratamiento_eliminarResponse> detalleTratamiento_eliminarAsync(OdontoSysBusiness.DetalleTratamientoWS.detalleTratamiento_eliminarRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webapplication.odontosys.edu.pucp.pe/DetalleTratamientoWA/detalleTratamien" +
            "to_obtenerPorIdRequest", ReplyAction="http://webapplication.odontosys.edu.pucp.pe/DetalleTratamientoWA/detalleTratamien" +
            "to_obtenerPorIdResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        OdontoSysBusiness.DetalleTratamientoWS.detalleTratamiento_obtenerPorIdResponse detalleTratamiento_obtenerPorId(OdontoSysBusiness.DetalleTratamientoWS.detalleTratamiento_obtenerPorIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webapplication.odontosys.edu.pucp.pe/DetalleTratamientoWA/detalleTratamien" +
            "to_obtenerPorIdRequest", ReplyAction="http://webapplication.odontosys.edu.pucp.pe/DetalleTratamientoWA/detalleTratamien" +
            "to_obtenerPorIdResponse")]
        System.Threading.Tasks.Task<OdontoSysBusiness.DetalleTratamientoWS.detalleTratamiento_obtenerPorIdResponse> detalleTratamiento_obtenerPorIdAsync(OdontoSysBusiness.DetalleTratamientoWS.detalleTratamiento_obtenerPorIdRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webapplication.odontosys.edu.pucp.pe/DetalleTratamientoWA/detalleTratamien" +
            "to_listarPorCitaRequest", ReplyAction="http://webapplication.odontosys.edu.pucp.pe/DetalleTratamientoWA/detalleTratamien" +
            "to_listarPorCitaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        OdontoSysBusiness.DetalleTratamientoWS.detalleTratamiento_listarPorCitaResponse detalleTratamiento_listarPorCita(OdontoSysBusiness.DetalleTratamientoWS.detalleTratamiento_listarPorCitaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webapplication.odontosys.edu.pucp.pe/DetalleTratamientoWA/detalleTratamien" +
            "to_listarPorCitaRequest", ReplyAction="http://webapplication.odontosys.edu.pucp.pe/DetalleTratamientoWA/detalleTratamien" +
            "to_listarPorCitaResponse")]
        System.Threading.Tasks.Task<OdontoSysBusiness.DetalleTratamientoWS.detalleTratamiento_listarPorCitaResponse> detalleTratamiento_listarPorCitaAsync(OdontoSysBusiness.DetalleTratamientoWS.detalleTratamiento_listarPorCitaRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webapplication.odontosys.edu.pucp.pe/DetalleTratamientoWA/detalleTratamien" +
            "to_modificarRequest", ReplyAction="http://webapplication.odontosys.edu.pucp.pe/DetalleTratamientoWA/detalleTratamien" +
            "to_modificarResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        OdontoSysBusiness.DetalleTratamientoWS.detalleTratamiento_modificarResponse detalleTratamiento_modificar(OdontoSysBusiness.DetalleTratamientoWS.detalleTratamiento_modificarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webapplication.odontosys.edu.pucp.pe/DetalleTratamientoWA/detalleTratamien" +
            "to_modificarRequest", ReplyAction="http://webapplication.odontosys.edu.pucp.pe/DetalleTratamientoWA/detalleTratamien" +
            "to_modificarResponse")]
        System.Threading.Tasks.Task<OdontoSysBusiness.DetalleTratamientoWS.detalleTratamiento_modificarResponse> detalleTratamiento_modificarAsync(OdontoSysBusiness.DetalleTratamientoWS.detalleTratamiento_modificarRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webapplication.odontosys.edu.pucp.pe/DetalleTratamientoWA/detalleTratamien" +
            "to_listarTodosRequest", ReplyAction="http://webapplication.odontosys.edu.pucp.pe/DetalleTratamientoWA/detalleTratamien" +
            "to_listarTodosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        OdontoSysBusiness.DetalleTratamientoWS.detalleTratamiento_listarTodosResponse detalleTratamiento_listarTodos(OdontoSysBusiness.DetalleTratamientoWS.detalleTratamiento_listarTodosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webapplication.odontosys.edu.pucp.pe/DetalleTratamientoWA/detalleTratamien" +
            "to_listarTodosRequest", ReplyAction="http://webapplication.odontosys.edu.pucp.pe/DetalleTratamientoWA/detalleTratamien" +
            "to_listarTodosResponse")]
        System.Threading.Tasks.Task<OdontoSysBusiness.DetalleTratamientoWS.detalleTratamiento_listarTodosResponse> detalleTratamiento_listarTodosAsync(OdontoSysBusiness.DetalleTratamientoWS.detalleTratamiento_listarTodosRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webapplication.odontosys.edu.pucp.pe/DetalleTratamientoWA/detalleTratamien" +
            "to_insertarRequest", ReplyAction="http://webapplication.odontosys.edu.pucp.pe/DetalleTratamientoWA/detalleTratamien" +
            "to_insertarResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        OdontoSysBusiness.DetalleTratamientoWS.detalleTratamiento_insertarResponse detalleTratamiento_insertar(OdontoSysBusiness.DetalleTratamientoWS.detalleTratamiento_insertarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webapplication.odontosys.edu.pucp.pe/DetalleTratamientoWA/detalleTratamien" +
            "to_insertarRequest", ReplyAction="http://webapplication.odontosys.edu.pucp.pe/DetalleTratamientoWA/detalleTratamien" +
            "to_insertarResponse")]
        System.Threading.Tasks.Task<OdontoSysBusiness.DetalleTratamientoWS.detalleTratamiento_insertarResponse> detalleTratamiento_insertarAsync(OdontoSysBusiness.DetalleTratamientoWS.detalleTratamiento_insertarRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="detalleTratamiento_actualizarSubtotal", WrapperNamespace="http://webapplication.odontosys.edu.pucp.pe/", IsWrapped=true)]
    public partial class detalleTratamiento_actualizarSubtotalRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webapplication.odontosys.edu.pucp.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idCta;
        
        public detalleTratamiento_actualizarSubtotalRequest() {
        }
        
        public detalleTratamiento_actualizarSubtotalRequest(int idCta) {
            this.idCta = idCta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="detalleTratamiento_actualizarSubtotalResponse", WrapperNamespace="http://webapplication.odontosys.edu.pucp.pe/", IsWrapped=true)]
    public partial class detalleTratamiento_actualizarSubtotalResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webapplication.odontosys.edu.pucp.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public detalleTratamiento_actualizarSubtotalResponse() {
        }
        
        public detalleTratamiento_actualizarSubtotalResponse(int @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webapplication.odontosys.edu.pucp.pe/")]
    public partial class detalleTratamiento : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int cantidadField;
        
        private bool cantidadFieldSpecified;
        
        private int idCitaField;
        
        private bool idCitaFieldSpecified;
        
        private double subtotalField;
        
        private tratamiento tratamientoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int cantidad {
            get {
                return this.cantidadField;
            }
            set {
                this.cantidadField = value;
                this.RaisePropertyChanged("cantidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cantidadSpecified {
            get {
                return this.cantidadFieldSpecified;
            }
            set {
                this.cantidadFieldSpecified = value;
                this.RaisePropertyChanged("cantidadSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int idCita {
            get {
                return this.idCitaField;
            }
            set {
                this.idCitaField = value;
                this.RaisePropertyChanged("idCita");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idCitaSpecified {
            get {
                return this.idCitaFieldSpecified;
            }
            set {
                this.idCitaFieldSpecified = value;
                this.RaisePropertyChanged("idCitaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public double subtotal {
            get {
                return this.subtotalField;
            }
            set {
                this.subtotalField = value;
                this.RaisePropertyChanged("subtotal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public tratamiento tratamiento {
            get {
                return this.tratamientoField;
            }
            set {
                this.tratamientoField = value;
                this.RaisePropertyChanged("tratamiento");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webapplication.odontosys.edu.pucp.pe/")]
    public partial class tratamiento : object, System.ComponentModel.INotifyPropertyChanged {
        
        private double costoField;
        
        private string descripcionField;
        
        private especialidad especialidadField;
        
        private int idTratamientoField;
        
        private bool idTratamientoFieldSpecified;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public double costo {
            get {
                return this.costoField;
            }
            set {
                this.costoField = value;
                this.RaisePropertyChanged("costo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public especialidad especialidad {
            get {
                return this.especialidadField;
            }
            set {
                this.especialidadField = value;
                this.RaisePropertyChanged("especialidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int idTratamiento {
            get {
                return this.idTratamientoField;
            }
            set {
                this.idTratamientoField = value;
                this.RaisePropertyChanged("idTratamiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idTratamientoSpecified {
            get {
                return this.idTratamientoFieldSpecified;
            }
            set {
                this.idTratamientoFieldSpecified = value;
                this.RaisePropertyChanged("idTratamientoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webapplication.odontosys.edu.pucp.pe/")]
    public partial class especialidad : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idEspecialidadField;
        
        private bool idEspecialidadFieldSpecified;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int idEspecialidad {
            get {
                return this.idEspecialidadField;
            }
            set {
                this.idEspecialidadField = value;
                this.RaisePropertyChanged("idEspecialidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idEspecialidadSpecified {
            get {
                return this.idEspecialidadFieldSpecified;
            }
            set {
                this.idEspecialidadFieldSpecified = value;
                this.RaisePropertyChanged("idEspecialidadSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="detalleTratamiento_eliminar", WrapperNamespace="http://webapplication.odontosys.edu.pucp.pe/", IsWrapped=true)]
    public partial class detalleTratamiento_eliminarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webapplication.odontosys.edu.pucp.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public OdontoSysBusiness.DetalleTratamientoWS.detalleTratamiento detalleTratamiento;
        
        public detalleTratamiento_eliminarRequest() {
        }
        
        public detalleTratamiento_eliminarRequest(OdontoSysBusiness.DetalleTratamientoWS.detalleTratamiento detalleTratamiento) {
            this.detalleTratamiento = detalleTratamiento;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="detalleTratamiento_eliminarResponse", WrapperNamespace="http://webapplication.odontosys.edu.pucp.pe/", IsWrapped=true)]
    public partial class detalleTratamiento_eliminarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webapplication.odontosys.edu.pucp.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public detalleTratamiento_eliminarResponse() {
        }
        
        public detalleTratamiento_eliminarResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="detalleTratamiento_obtenerPorId", WrapperNamespace="http://webapplication.odontosys.edu.pucp.pe/", IsWrapped=true)]
    public partial class detalleTratamiento_obtenerPorIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webapplication.odontosys.edu.pucp.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public detalleTratamiento_obtenerPorIdRequest() {
        }
        
        public detalleTratamiento_obtenerPorIdRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="detalleTratamiento_obtenerPorIdResponse", WrapperNamespace="http://webapplication.odontosys.edu.pucp.pe/", IsWrapped=true)]
    public partial class detalleTratamiento_obtenerPorIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webapplication.odontosys.edu.pucp.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public OdontoSysBusiness.DetalleTratamientoWS.detalleTratamiento @return;
        
        public detalleTratamiento_obtenerPorIdResponse() {
        }
        
        public detalleTratamiento_obtenerPorIdResponse(OdontoSysBusiness.DetalleTratamientoWS.detalleTratamiento @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="detalleTratamiento_listarPorCita", WrapperNamespace="http://webapplication.odontosys.edu.pucp.pe/", IsWrapped=true)]
    public partial class detalleTratamiento_listarPorCitaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webapplication.odontosys.edu.pucp.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idCta;
        
        public detalleTratamiento_listarPorCitaRequest() {
        }
        
        public detalleTratamiento_listarPorCitaRequest(int idCta) {
            this.idCta = idCta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="detalleTratamiento_listarPorCitaResponse", WrapperNamespace="http://webapplication.odontosys.edu.pucp.pe/", IsWrapped=true)]
    public partial class detalleTratamiento_listarPorCitaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webapplication.odontosys.edu.pucp.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public OdontoSysBusiness.DetalleTratamientoWS.detalleTratamiento[] @return;
        
        public detalleTratamiento_listarPorCitaResponse() {
        }
        
        public detalleTratamiento_listarPorCitaResponse(OdontoSysBusiness.DetalleTratamientoWS.detalleTratamiento[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="detalleTratamiento_modificar", WrapperNamespace="http://webapplication.odontosys.edu.pucp.pe/", IsWrapped=true)]
    public partial class detalleTratamiento_modificarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webapplication.odontosys.edu.pucp.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public OdontoSysBusiness.DetalleTratamientoWS.detalleTratamiento detalleTratamiento;
        
        public detalleTratamiento_modificarRequest() {
        }
        
        public detalleTratamiento_modificarRequest(OdontoSysBusiness.DetalleTratamientoWS.detalleTratamiento detalleTratamiento) {
            this.detalleTratamiento = detalleTratamiento;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="detalleTratamiento_modificarResponse", WrapperNamespace="http://webapplication.odontosys.edu.pucp.pe/", IsWrapped=true)]
    public partial class detalleTratamiento_modificarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webapplication.odontosys.edu.pucp.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public detalleTratamiento_modificarResponse() {
        }
        
        public detalleTratamiento_modificarResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="detalleTratamiento_listarTodos", WrapperNamespace="http://webapplication.odontosys.edu.pucp.pe/", IsWrapped=true)]
    public partial class detalleTratamiento_listarTodosRequest {
        
        public detalleTratamiento_listarTodosRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="detalleTratamiento_listarTodosResponse", WrapperNamespace="http://webapplication.odontosys.edu.pucp.pe/", IsWrapped=true)]
    public partial class detalleTratamiento_listarTodosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webapplication.odontosys.edu.pucp.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public OdontoSysBusiness.DetalleTratamientoWS.detalleTratamiento[] @return;
        
        public detalleTratamiento_listarTodosResponse() {
        }
        
        public detalleTratamiento_listarTodosResponse(OdontoSysBusiness.DetalleTratamientoWS.detalleTratamiento[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="detalleTratamiento_insertar", WrapperNamespace="http://webapplication.odontosys.edu.pucp.pe/", IsWrapped=true)]
    public partial class detalleTratamiento_insertarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webapplication.odontosys.edu.pucp.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public OdontoSysBusiness.DetalleTratamientoWS.detalleTratamiento detalleTratamiento;
        
        public detalleTratamiento_insertarRequest() {
        }
        
        public detalleTratamiento_insertarRequest(OdontoSysBusiness.DetalleTratamientoWS.detalleTratamiento detalleTratamiento) {
            this.detalleTratamiento = detalleTratamiento;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="detalleTratamiento_insertarResponse", WrapperNamespace="http://webapplication.odontosys.edu.pucp.pe/", IsWrapped=true)]
    public partial class detalleTratamiento_insertarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webapplication.odontosys.edu.pucp.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public detalleTratamiento_insertarResponse() {
        }
        
        public detalleTratamiento_insertarResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DetalleTratamientoWAChannel : OdontoSysBusiness.DetalleTratamientoWS.DetalleTratamientoWA, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DetalleTratamientoWAClient : System.ServiceModel.ClientBase<OdontoSysBusiness.DetalleTratamientoWS.DetalleTratamientoWA>, OdontoSysBusiness.DetalleTratamientoWS.DetalleTratamientoWA {
        
        public DetalleTratamientoWAClient() {
        }
        
        public DetalleTratamientoWAClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DetalleTratamientoWAClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DetalleTratamientoWAClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DetalleTratamientoWAClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OdontoSysBusiness.DetalleTratamientoWS.detalleTratamiento_actualizarSubtotalResponse OdontoSysBusiness.DetalleTratamientoWS.DetalleTratamientoWA.detalleTratamiento_actualizarSubtotal(OdontoSysBusiness.DetalleTratamientoWS.detalleTratamiento_actualizarSubtotalRequest request) {
            return base.Channel.detalleTratamiento_actualizarSubtotal(request);
        }
        
        public int detalleTratamiento_actualizarSubtotal(int idCta) {
            OdontoSysBusiness.DetalleTratamientoWS.detalleTratamiento_actualizarSubtotalRequest inValue = new OdontoSysBusiness.DetalleTratamientoWS.detalleTratamiento_actualizarSubtotalRequest();
            inValue.idCta = idCta;
            OdontoSysBusiness.DetalleTratamientoWS.detalleTratamiento_actualizarSubtotalResponse retVal = ((OdontoSysBusiness.DetalleTratamientoWS.DetalleTratamientoWA)(this)).detalleTratamiento_actualizarSubtotal(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OdontoSysBusiness.DetalleTratamientoWS.detalleTratamiento_actualizarSubtotalResponse> OdontoSysBusiness.DetalleTratamientoWS.DetalleTratamientoWA.detalleTratamiento_actualizarSubtotalAsync(OdontoSysBusiness.DetalleTratamientoWS.detalleTratamiento_actualizarSubtotalRequest request) {
            return base.Channel.detalleTratamiento_actualizarSubtotalAsync(request);
        }
        
        public System.Threading.Tasks.Task<OdontoSysBusiness.DetalleTratamientoWS.detalleTratamiento_actualizarSubtotalResponse> detalleTratamiento_actualizarSubtotalAsync(int idCta) {
            OdontoSysBusiness.DetalleTratamientoWS.detalleTratamiento_actualizarSubtotalRequest inValue = new OdontoSysBusiness.DetalleTratamientoWS.detalleTratamiento_actualizarSubtotalRequest();
            inValue.idCta = idCta;
            return ((OdontoSysBusiness.DetalleTratamientoWS.DetalleTratamientoWA)(this)).detalleTratamiento_actualizarSubtotalAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OdontoSysBusiness.DetalleTratamientoWS.detalleTratamiento_eliminarResponse OdontoSysBusiness.DetalleTratamientoWS.DetalleTratamientoWA.detalleTratamiento_eliminar(OdontoSysBusiness.DetalleTratamientoWS.detalleTratamiento_eliminarRequest request) {
            return base.Channel.detalleTratamiento_eliminar(request);
        }
        
        public int detalleTratamiento_eliminar(OdontoSysBusiness.DetalleTratamientoWS.detalleTratamiento detalleTratamiento) {
            OdontoSysBusiness.DetalleTratamientoWS.detalleTratamiento_eliminarRequest inValue = new OdontoSysBusiness.DetalleTratamientoWS.detalleTratamiento_eliminarRequest();
            inValue.detalleTratamiento = detalleTratamiento;
            OdontoSysBusiness.DetalleTratamientoWS.detalleTratamiento_eliminarResponse retVal = ((OdontoSysBusiness.DetalleTratamientoWS.DetalleTratamientoWA)(this)).detalleTratamiento_eliminar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OdontoSysBusiness.DetalleTratamientoWS.detalleTratamiento_eliminarResponse> OdontoSysBusiness.DetalleTratamientoWS.DetalleTratamientoWA.detalleTratamiento_eliminarAsync(OdontoSysBusiness.DetalleTratamientoWS.detalleTratamiento_eliminarRequest request) {
            return base.Channel.detalleTratamiento_eliminarAsync(request);
        }
        
        public System.Threading.Tasks.Task<OdontoSysBusiness.DetalleTratamientoWS.detalleTratamiento_eliminarResponse> detalleTratamiento_eliminarAsync(OdontoSysBusiness.DetalleTratamientoWS.detalleTratamiento detalleTratamiento) {
            OdontoSysBusiness.DetalleTratamientoWS.detalleTratamiento_eliminarRequest inValue = new OdontoSysBusiness.DetalleTratamientoWS.detalleTratamiento_eliminarRequest();
            inValue.detalleTratamiento = detalleTratamiento;
            return ((OdontoSysBusiness.DetalleTratamientoWS.DetalleTratamientoWA)(this)).detalleTratamiento_eliminarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OdontoSysBusiness.DetalleTratamientoWS.detalleTratamiento_obtenerPorIdResponse OdontoSysBusiness.DetalleTratamientoWS.DetalleTratamientoWA.detalleTratamiento_obtenerPorId(OdontoSysBusiness.DetalleTratamientoWS.detalleTratamiento_obtenerPorIdRequest request) {
            return base.Channel.detalleTratamiento_obtenerPorId(request);
        }
        
        public OdontoSysBusiness.DetalleTratamientoWS.detalleTratamiento detalleTratamiento_obtenerPorId(int id) {
            OdontoSysBusiness.DetalleTratamientoWS.detalleTratamiento_obtenerPorIdRequest inValue = new OdontoSysBusiness.DetalleTratamientoWS.detalleTratamiento_obtenerPorIdRequest();
            inValue.id = id;
            OdontoSysBusiness.DetalleTratamientoWS.detalleTratamiento_obtenerPorIdResponse retVal = ((OdontoSysBusiness.DetalleTratamientoWS.DetalleTratamientoWA)(this)).detalleTratamiento_obtenerPorId(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OdontoSysBusiness.DetalleTratamientoWS.detalleTratamiento_obtenerPorIdResponse> OdontoSysBusiness.DetalleTratamientoWS.DetalleTratamientoWA.detalleTratamiento_obtenerPorIdAsync(OdontoSysBusiness.DetalleTratamientoWS.detalleTratamiento_obtenerPorIdRequest request) {
            return base.Channel.detalleTratamiento_obtenerPorIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<OdontoSysBusiness.DetalleTratamientoWS.detalleTratamiento_obtenerPorIdResponse> detalleTratamiento_obtenerPorIdAsync(int id) {
            OdontoSysBusiness.DetalleTratamientoWS.detalleTratamiento_obtenerPorIdRequest inValue = new OdontoSysBusiness.DetalleTratamientoWS.detalleTratamiento_obtenerPorIdRequest();
            inValue.id = id;
            return ((OdontoSysBusiness.DetalleTratamientoWS.DetalleTratamientoWA)(this)).detalleTratamiento_obtenerPorIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OdontoSysBusiness.DetalleTratamientoWS.detalleTratamiento_listarPorCitaResponse OdontoSysBusiness.DetalleTratamientoWS.DetalleTratamientoWA.detalleTratamiento_listarPorCita(OdontoSysBusiness.DetalleTratamientoWS.detalleTratamiento_listarPorCitaRequest request) {
            return base.Channel.detalleTratamiento_listarPorCita(request);
        }
        
        public OdontoSysBusiness.DetalleTratamientoWS.detalleTratamiento[] detalleTratamiento_listarPorCita(int idCta) {
            OdontoSysBusiness.DetalleTratamientoWS.detalleTratamiento_listarPorCitaRequest inValue = new OdontoSysBusiness.DetalleTratamientoWS.detalleTratamiento_listarPorCitaRequest();
            inValue.idCta = idCta;
            OdontoSysBusiness.DetalleTratamientoWS.detalleTratamiento_listarPorCitaResponse retVal = ((OdontoSysBusiness.DetalleTratamientoWS.DetalleTratamientoWA)(this)).detalleTratamiento_listarPorCita(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OdontoSysBusiness.DetalleTratamientoWS.detalleTratamiento_listarPorCitaResponse> OdontoSysBusiness.DetalleTratamientoWS.DetalleTratamientoWA.detalleTratamiento_listarPorCitaAsync(OdontoSysBusiness.DetalleTratamientoWS.detalleTratamiento_listarPorCitaRequest request) {
            return base.Channel.detalleTratamiento_listarPorCitaAsync(request);
        }
        
        public System.Threading.Tasks.Task<OdontoSysBusiness.DetalleTratamientoWS.detalleTratamiento_listarPorCitaResponse> detalleTratamiento_listarPorCitaAsync(int idCta) {
            OdontoSysBusiness.DetalleTratamientoWS.detalleTratamiento_listarPorCitaRequest inValue = new OdontoSysBusiness.DetalleTratamientoWS.detalleTratamiento_listarPorCitaRequest();
            inValue.idCta = idCta;
            return ((OdontoSysBusiness.DetalleTratamientoWS.DetalleTratamientoWA)(this)).detalleTratamiento_listarPorCitaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OdontoSysBusiness.DetalleTratamientoWS.detalleTratamiento_modificarResponse OdontoSysBusiness.DetalleTratamientoWS.DetalleTratamientoWA.detalleTratamiento_modificar(OdontoSysBusiness.DetalleTratamientoWS.detalleTratamiento_modificarRequest request) {
            return base.Channel.detalleTratamiento_modificar(request);
        }
        
        public int detalleTratamiento_modificar(OdontoSysBusiness.DetalleTratamientoWS.detalleTratamiento detalleTratamiento) {
            OdontoSysBusiness.DetalleTratamientoWS.detalleTratamiento_modificarRequest inValue = new OdontoSysBusiness.DetalleTratamientoWS.detalleTratamiento_modificarRequest();
            inValue.detalleTratamiento = detalleTratamiento;
            OdontoSysBusiness.DetalleTratamientoWS.detalleTratamiento_modificarResponse retVal = ((OdontoSysBusiness.DetalleTratamientoWS.DetalleTratamientoWA)(this)).detalleTratamiento_modificar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OdontoSysBusiness.DetalleTratamientoWS.detalleTratamiento_modificarResponse> OdontoSysBusiness.DetalleTratamientoWS.DetalleTratamientoWA.detalleTratamiento_modificarAsync(OdontoSysBusiness.DetalleTratamientoWS.detalleTratamiento_modificarRequest request) {
            return base.Channel.detalleTratamiento_modificarAsync(request);
        }
        
        public System.Threading.Tasks.Task<OdontoSysBusiness.DetalleTratamientoWS.detalleTratamiento_modificarResponse> detalleTratamiento_modificarAsync(OdontoSysBusiness.DetalleTratamientoWS.detalleTratamiento detalleTratamiento) {
            OdontoSysBusiness.DetalleTratamientoWS.detalleTratamiento_modificarRequest inValue = new OdontoSysBusiness.DetalleTratamientoWS.detalleTratamiento_modificarRequest();
            inValue.detalleTratamiento = detalleTratamiento;
            return ((OdontoSysBusiness.DetalleTratamientoWS.DetalleTratamientoWA)(this)).detalleTratamiento_modificarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OdontoSysBusiness.DetalleTratamientoWS.detalleTratamiento_listarTodosResponse OdontoSysBusiness.DetalleTratamientoWS.DetalleTratamientoWA.detalleTratamiento_listarTodos(OdontoSysBusiness.DetalleTratamientoWS.detalleTratamiento_listarTodosRequest request) {
            return base.Channel.detalleTratamiento_listarTodos(request);
        }
        
        public OdontoSysBusiness.DetalleTratamientoWS.detalleTratamiento[] detalleTratamiento_listarTodos() {
            OdontoSysBusiness.DetalleTratamientoWS.detalleTratamiento_listarTodosRequest inValue = new OdontoSysBusiness.DetalleTratamientoWS.detalleTratamiento_listarTodosRequest();
            OdontoSysBusiness.DetalleTratamientoWS.detalleTratamiento_listarTodosResponse retVal = ((OdontoSysBusiness.DetalleTratamientoWS.DetalleTratamientoWA)(this)).detalleTratamiento_listarTodos(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OdontoSysBusiness.DetalleTratamientoWS.detalleTratamiento_listarTodosResponse> OdontoSysBusiness.DetalleTratamientoWS.DetalleTratamientoWA.detalleTratamiento_listarTodosAsync(OdontoSysBusiness.DetalleTratamientoWS.detalleTratamiento_listarTodosRequest request) {
            return base.Channel.detalleTratamiento_listarTodosAsync(request);
        }
        
        public System.Threading.Tasks.Task<OdontoSysBusiness.DetalleTratamientoWS.detalleTratamiento_listarTodosResponse> detalleTratamiento_listarTodosAsync() {
            OdontoSysBusiness.DetalleTratamientoWS.detalleTratamiento_listarTodosRequest inValue = new OdontoSysBusiness.DetalleTratamientoWS.detalleTratamiento_listarTodosRequest();
            return ((OdontoSysBusiness.DetalleTratamientoWS.DetalleTratamientoWA)(this)).detalleTratamiento_listarTodosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OdontoSysBusiness.DetalleTratamientoWS.detalleTratamiento_insertarResponse OdontoSysBusiness.DetalleTratamientoWS.DetalleTratamientoWA.detalleTratamiento_insertar(OdontoSysBusiness.DetalleTratamientoWS.detalleTratamiento_insertarRequest request) {
            return base.Channel.detalleTratamiento_insertar(request);
        }
        
        public int detalleTratamiento_insertar(OdontoSysBusiness.DetalleTratamientoWS.detalleTratamiento detalleTratamiento) {
            OdontoSysBusiness.DetalleTratamientoWS.detalleTratamiento_insertarRequest inValue = new OdontoSysBusiness.DetalleTratamientoWS.detalleTratamiento_insertarRequest();
            inValue.detalleTratamiento = detalleTratamiento;
            OdontoSysBusiness.DetalleTratamientoWS.detalleTratamiento_insertarResponse retVal = ((OdontoSysBusiness.DetalleTratamientoWS.DetalleTratamientoWA)(this)).detalleTratamiento_insertar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OdontoSysBusiness.DetalleTratamientoWS.detalleTratamiento_insertarResponse> OdontoSysBusiness.DetalleTratamientoWS.DetalleTratamientoWA.detalleTratamiento_insertarAsync(OdontoSysBusiness.DetalleTratamientoWS.detalleTratamiento_insertarRequest request) {
            return base.Channel.detalleTratamiento_insertarAsync(request);
        }
        
        public System.Threading.Tasks.Task<OdontoSysBusiness.DetalleTratamientoWS.detalleTratamiento_insertarResponse> detalleTratamiento_insertarAsync(OdontoSysBusiness.DetalleTratamientoWS.detalleTratamiento detalleTratamiento) {
            OdontoSysBusiness.DetalleTratamientoWS.detalleTratamiento_insertarRequest inValue = new OdontoSysBusiness.DetalleTratamientoWS.detalleTratamiento_insertarRequest();
            inValue.detalleTratamiento = detalleTratamiento;
            return ((OdontoSysBusiness.DetalleTratamientoWS.DetalleTratamientoWA)(this)).detalleTratamiento_insertarAsync(inValue);
        }
    }
}
