SET SQL_SAFE_UPDATES = 0;

USE ODONTO_SYS;

SELECT * FROM OS_CITAS;
SELECT * FROM OS_COMPROBANTES;
SELECT * FROM OS_DETALLES_TRATAMIENTOS;
SELECT * FROM OS_ESPECIALIDADES;
SELECT * FROM OS_METODOS_PAGOS;
SELECT * FROM OS_ODONTOLOGOS;
SELECT * FROM OS_PACIENTES;
SELECT * FROM OS_RECEPCIONISTAS;
SELECT * FROM OS_SALAS;
SELECT * FROM OS_TIPOS_DOCUMENTOS;
SELECT * FROM OS_TRATAMIENTOS;
SELECT * FROM OS_TURNOS;
SELECT * FROM OS_TURNOS_POR_ODONTOLOGOS;
SELECT * FROM OS_VALORACIONES;
