//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OdontoSysBusiness.turnoxodontologoWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://wa.odontosys.com/", ConfigurationName="turnoxodontologoWS.TurnosXOdontologo")]
    public interface TurnosXOdontologo {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://wa.odontosys.com/TurnosXOdontologo/TurnoListarPorOdontologoRequest", ReplyAction="http://wa.odontosys.com/TurnosXOdontologo/TurnoListarPorOdontologoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        OdontoSysBusiness.turnoxodontologoWS.TurnoListarPorOdontologoResponse TurnoListarPorOdontologo(OdontoSysBusiness.turnoxodontologoWS.TurnoListarPorOdontologoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wa.odontosys.com/TurnosXOdontologo/TurnoListarPorOdontologoRequest", ReplyAction="http://wa.odontosys.com/TurnosXOdontologo/TurnoListarPorOdontologoResponse")]
        System.Threading.Tasks.Task<OdontoSysBusiness.turnoxodontologoWS.TurnoListarPorOdontologoResponse> TurnoListarPorOdontologoAsync(OdontoSysBusiness.turnoxodontologoWS.TurnoListarPorOdontologoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://wa.odontosys.com/TurnosXOdontologo/EliminarTurnoXOdontologoRequest", ReplyAction="http://wa.odontosys.com/TurnosXOdontologo/EliminarTurnoXOdontologoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        OdontoSysBusiness.turnoxodontologoWS.EliminarTurnoXOdontologoResponse EliminarTurnoXOdontologo(OdontoSysBusiness.turnoxodontologoWS.EliminarTurnoXOdontologoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wa.odontosys.com/TurnosXOdontologo/EliminarTurnoXOdontologoRequest", ReplyAction="http://wa.odontosys.com/TurnosXOdontologo/EliminarTurnoXOdontologoResponse")]
        System.Threading.Tasks.Task<OdontoSysBusiness.turnoxodontologoWS.EliminarTurnoXOdontologoResponse> EliminarTurnoXOdontologoAsync(OdontoSysBusiness.turnoxodontologoWS.EliminarTurnoXOdontologoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://wa.odontosys.com/TurnosXOdontologo/InsertarTurnoXOdontologoRequest", ReplyAction="http://wa.odontosys.com/TurnosXOdontologo/InsertarTurnoXOdontologoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        OdontoSysBusiness.turnoxodontologoWS.InsertarTurnoXOdontologoResponse InsertarTurnoXOdontologo(OdontoSysBusiness.turnoxodontologoWS.InsertarTurnoXOdontologoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wa.odontosys.com/TurnosXOdontologo/InsertarTurnoXOdontologoRequest", ReplyAction="http://wa.odontosys.com/TurnosXOdontologo/InsertarTurnoXOdontologoResponse")]
        System.Threading.Tasks.Task<OdontoSysBusiness.turnoxodontologoWS.InsertarTurnoXOdontologoResponse> InsertarTurnoXOdontologoAsync(OdontoSysBusiness.turnoxodontologoWS.InsertarTurnoXOdontologoRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wa.odontosys.com/")]
    public partial class turnoXOdontologo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idOdontologoField;
        
        private int idTurnoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int idOdontologo {
            get {
                return this.idOdontologoField;
            }
            set {
                this.idOdontologoField = value;
                this.RaisePropertyChanged("idOdontologo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int idTurno {
            get {
                return this.idTurnoField;
            }
            set {
                this.idTurnoField = value;
                this.RaisePropertyChanged("idTurno");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TurnoListarPorOdontologo", WrapperNamespace="http://wa.odontosys.com/", IsWrapped=true)]
    public partial class TurnoListarPorOdontologoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wa.odontosys.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idOdontologo;
        
        public TurnoListarPorOdontologoRequest() {
        }
        
        public TurnoListarPorOdontologoRequest(int idOdontologo) {
            this.idOdontologo = idOdontologo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TurnoListarPorOdontologoResponse", WrapperNamespace="http://wa.odontosys.com/", IsWrapped=true)]
    public partial class TurnoListarPorOdontologoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wa.odontosys.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public OdontoSysBusiness.turnoxodontologoWS.turnoXOdontologo[] @return;
        
        public TurnoListarPorOdontologoResponse() {
        }
        
        public TurnoListarPorOdontologoResponse(OdontoSysBusiness.turnoxodontologoWS.turnoXOdontologo[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EliminarTurnoXOdontologo", WrapperNamespace="http://wa.odontosys.com/", IsWrapped=true)]
    public partial class EliminarTurnoXOdontologoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wa.odontosys.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public OdontoSysBusiness.turnoxodontologoWS.turnoXOdontologo turnoXOdontologo;
        
        public EliminarTurnoXOdontologoRequest() {
        }
        
        public EliminarTurnoXOdontologoRequest(OdontoSysBusiness.turnoxodontologoWS.turnoXOdontologo turnoXOdontologo) {
            this.turnoXOdontologo = turnoXOdontologo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EliminarTurnoXOdontologoResponse", WrapperNamespace="http://wa.odontosys.com/", IsWrapped=true)]
    public partial class EliminarTurnoXOdontologoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wa.odontosys.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public EliminarTurnoXOdontologoResponse() {
        }
        
        public EliminarTurnoXOdontologoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertarTurnoXOdontologo", WrapperNamespace="http://wa.odontosys.com/", IsWrapped=true)]
    public partial class InsertarTurnoXOdontologoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wa.odontosys.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public OdontoSysBusiness.turnoxodontologoWS.turnoXOdontologo turnoXOdontologo;
        
        public InsertarTurnoXOdontologoRequest() {
        }
        
        public InsertarTurnoXOdontologoRequest(OdontoSysBusiness.turnoxodontologoWS.turnoXOdontologo turnoXOdontologo) {
            this.turnoXOdontologo = turnoXOdontologo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertarTurnoXOdontologoResponse", WrapperNamespace="http://wa.odontosys.com/", IsWrapped=true)]
    public partial class InsertarTurnoXOdontologoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wa.odontosys.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public InsertarTurnoXOdontologoResponse() {
        }
        
        public InsertarTurnoXOdontologoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TurnosXOdontologoChannel : OdontoSysBusiness.turnoxodontologoWS.TurnosXOdontologo, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TurnosXOdontologoClient : System.ServiceModel.ClientBase<OdontoSysBusiness.turnoxodontologoWS.TurnosXOdontologo>, OdontoSysBusiness.turnoxodontologoWS.TurnosXOdontologo {
        
        public TurnosXOdontologoClient() {
        }
        
        public TurnosXOdontologoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TurnosXOdontologoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TurnosXOdontologoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TurnosXOdontologoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OdontoSysBusiness.turnoxodontologoWS.TurnoListarPorOdontologoResponse OdontoSysBusiness.turnoxodontologoWS.TurnosXOdontologo.TurnoListarPorOdontologo(OdontoSysBusiness.turnoxodontologoWS.TurnoListarPorOdontologoRequest request) {
            return base.Channel.TurnoListarPorOdontologo(request);
        }
        
        public OdontoSysBusiness.turnoxodontologoWS.turnoXOdontologo[] TurnoListarPorOdontologo(int idOdontologo) {
            OdontoSysBusiness.turnoxodontologoWS.TurnoListarPorOdontologoRequest inValue = new OdontoSysBusiness.turnoxodontologoWS.TurnoListarPorOdontologoRequest();
            inValue.idOdontologo = idOdontologo;
            OdontoSysBusiness.turnoxodontologoWS.TurnoListarPorOdontologoResponse retVal = ((OdontoSysBusiness.turnoxodontologoWS.TurnosXOdontologo)(this)).TurnoListarPorOdontologo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OdontoSysBusiness.turnoxodontologoWS.TurnoListarPorOdontologoResponse> OdontoSysBusiness.turnoxodontologoWS.TurnosXOdontologo.TurnoListarPorOdontologoAsync(OdontoSysBusiness.turnoxodontologoWS.TurnoListarPorOdontologoRequest request) {
            return base.Channel.TurnoListarPorOdontologoAsync(request);
        }
        
        public System.Threading.Tasks.Task<OdontoSysBusiness.turnoxodontologoWS.TurnoListarPorOdontologoResponse> TurnoListarPorOdontologoAsync(int idOdontologo) {
            OdontoSysBusiness.turnoxodontologoWS.TurnoListarPorOdontologoRequest inValue = new OdontoSysBusiness.turnoxodontologoWS.TurnoListarPorOdontologoRequest();
            inValue.idOdontologo = idOdontologo;
            return ((OdontoSysBusiness.turnoxodontologoWS.TurnosXOdontologo)(this)).TurnoListarPorOdontologoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OdontoSysBusiness.turnoxodontologoWS.EliminarTurnoXOdontologoResponse OdontoSysBusiness.turnoxodontologoWS.TurnosXOdontologo.EliminarTurnoXOdontologo(OdontoSysBusiness.turnoxodontologoWS.EliminarTurnoXOdontologoRequest request) {
            return base.Channel.EliminarTurnoXOdontologo(request);
        }
        
        public int EliminarTurnoXOdontologo(OdontoSysBusiness.turnoxodontologoWS.turnoXOdontologo turnoXOdontologo) {
            OdontoSysBusiness.turnoxodontologoWS.EliminarTurnoXOdontologoRequest inValue = new OdontoSysBusiness.turnoxodontologoWS.EliminarTurnoXOdontologoRequest();
            inValue.turnoXOdontologo = turnoXOdontologo;
            OdontoSysBusiness.turnoxodontologoWS.EliminarTurnoXOdontologoResponse retVal = ((OdontoSysBusiness.turnoxodontologoWS.TurnosXOdontologo)(this)).EliminarTurnoXOdontologo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OdontoSysBusiness.turnoxodontologoWS.EliminarTurnoXOdontologoResponse> OdontoSysBusiness.turnoxodontologoWS.TurnosXOdontologo.EliminarTurnoXOdontologoAsync(OdontoSysBusiness.turnoxodontologoWS.EliminarTurnoXOdontologoRequest request) {
            return base.Channel.EliminarTurnoXOdontologoAsync(request);
        }
        
        public System.Threading.Tasks.Task<OdontoSysBusiness.turnoxodontologoWS.EliminarTurnoXOdontologoResponse> EliminarTurnoXOdontologoAsync(OdontoSysBusiness.turnoxodontologoWS.turnoXOdontologo turnoXOdontologo) {
            OdontoSysBusiness.turnoxodontologoWS.EliminarTurnoXOdontologoRequest inValue = new OdontoSysBusiness.turnoxodontologoWS.EliminarTurnoXOdontologoRequest();
            inValue.turnoXOdontologo = turnoXOdontologo;
            return ((OdontoSysBusiness.turnoxodontologoWS.TurnosXOdontologo)(this)).EliminarTurnoXOdontologoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OdontoSysBusiness.turnoxodontologoWS.InsertarTurnoXOdontologoResponse OdontoSysBusiness.turnoxodontologoWS.TurnosXOdontologo.InsertarTurnoXOdontologo(OdontoSysBusiness.turnoxodontologoWS.InsertarTurnoXOdontologoRequest request) {
            return base.Channel.InsertarTurnoXOdontologo(request);
        }
        
        public int InsertarTurnoXOdontologo(OdontoSysBusiness.turnoxodontologoWS.turnoXOdontologo turnoXOdontologo) {
            OdontoSysBusiness.turnoxodontologoWS.InsertarTurnoXOdontologoRequest inValue = new OdontoSysBusiness.turnoxodontologoWS.InsertarTurnoXOdontologoRequest();
            inValue.turnoXOdontologo = turnoXOdontologo;
            OdontoSysBusiness.turnoxodontologoWS.InsertarTurnoXOdontologoResponse retVal = ((OdontoSysBusiness.turnoxodontologoWS.TurnosXOdontologo)(this)).InsertarTurnoXOdontologo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OdontoSysBusiness.turnoxodontologoWS.InsertarTurnoXOdontologoResponse> OdontoSysBusiness.turnoxodontologoWS.TurnosXOdontologo.InsertarTurnoXOdontologoAsync(OdontoSysBusiness.turnoxodontologoWS.InsertarTurnoXOdontologoRequest request) {
            return base.Channel.InsertarTurnoXOdontologoAsync(request);
        }
        
        public System.Threading.Tasks.Task<OdontoSysBusiness.turnoxodontologoWS.InsertarTurnoXOdontologoResponse> InsertarTurnoXOdontologoAsync(OdontoSysBusiness.turnoxodontologoWS.turnoXOdontologo turnoXOdontologo) {
            OdontoSysBusiness.turnoxodontologoWS.InsertarTurnoXOdontologoRequest inValue = new OdontoSysBusiness.turnoxodontologoWS.InsertarTurnoXOdontologoRequest();
            inValue.turnoXOdontologo = turnoXOdontologo;
            return ((OdontoSysBusiness.turnoxodontologoWS.TurnosXOdontologo)(this)).InsertarTurnoXOdontologoAsync(inValue);
        }
    }
}
