//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OdontoSysBusiness.TipoDocumentoWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webapplication.odontosys.edu.pucp.pe/", ConfigurationName="TipoDocumentoWS.TipoDocumentoWA")]
    public interface TipoDocumentoWA {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webapplication.odontosys.edu.pucp.pe/TipoDocumentoWA/tipoDocumento_obtener" +
            "PorIdRequest", ReplyAction="http://webapplication.odontosys.edu.pucp.pe/TipoDocumentoWA/tipoDocumento_obtener" +
            "PorIdResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        OdontoSysBusiness.TipoDocumentoWS.tipoDocumento_obtenerPorIdResponse tipoDocumento_obtenerPorId(OdontoSysBusiness.TipoDocumentoWS.tipoDocumento_obtenerPorIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webapplication.odontosys.edu.pucp.pe/TipoDocumentoWA/tipoDocumento_obtener" +
            "PorIdRequest", ReplyAction="http://webapplication.odontosys.edu.pucp.pe/TipoDocumentoWA/tipoDocumento_obtener" +
            "PorIdResponse")]
        System.Threading.Tasks.Task<OdontoSysBusiness.TipoDocumentoWS.tipoDocumento_obtenerPorIdResponse> tipoDocumento_obtenerPorIdAsync(OdontoSysBusiness.TipoDocumentoWS.tipoDocumento_obtenerPorIdRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webapplication.odontosys.edu.pucp.pe/TipoDocumentoWA/tipoDocumento_inserta" +
            "rRequest", ReplyAction="http://webapplication.odontosys.edu.pucp.pe/TipoDocumentoWA/tipoDocumento_inserta" +
            "rResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        OdontoSysBusiness.TipoDocumentoWS.tipoDocumento_insertarResponse tipoDocumento_insertar(OdontoSysBusiness.TipoDocumentoWS.tipoDocumento_insertarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webapplication.odontosys.edu.pucp.pe/TipoDocumentoWA/tipoDocumento_inserta" +
            "rRequest", ReplyAction="http://webapplication.odontosys.edu.pucp.pe/TipoDocumentoWA/tipoDocumento_inserta" +
            "rResponse")]
        System.Threading.Tasks.Task<OdontoSysBusiness.TipoDocumentoWS.tipoDocumento_insertarResponse> tipoDocumento_insertarAsync(OdontoSysBusiness.TipoDocumentoWS.tipoDocumento_insertarRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webapplication.odontosys.edu.pucp.pe/TipoDocumentoWA/tipoDocumento_elimina" +
            "rRequest", ReplyAction="http://webapplication.odontosys.edu.pucp.pe/TipoDocumentoWA/tipoDocumento_elimina" +
            "rResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        OdontoSysBusiness.TipoDocumentoWS.tipoDocumento_eliminarResponse tipoDocumento_eliminar(OdontoSysBusiness.TipoDocumentoWS.tipoDocumento_eliminarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webapplication.odontosys.edu.pucp.pe/TipoDocumentoWA/tipoDocumento_elimina" +
            "rRequest", ReplyAction="http://webapplication.odontosys.edu.pucp.pe/TipoDocumentoWA/tipoDocumento_elimina" +
            "rResponse")]
        System.Threading.Tasks.Task<OdontoSysBusiness.TipoDocumentoWS.tipoDocumento_eliminarResponse> tipoDocumento_eliminarAsync(OdontoSysBusiness.TipoDocumentoWS.tipoDocumento_eliminarRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webapplication.odontosys.edu.pucp.pe/TipoDocumentoWA/tipoDocumento_modific" +
            "arRequest", ReplyAction="http://webapplication.odontosys.edu.pucp.pe/TipoDocumentoWA/tipoDocumento_modific" +
            "arResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        OdontoSysBusiness.TipoDocumentoWS.tipoDocumento_modificarResponse tipoDocumento_modificar(OdontoSysBusiness.TipoDocumentoWS.tipoDocumento_modificarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webapplication.odontosys.edu.pucp.pe/TipoDocumentoWA/tipoDocumento_modific" +
            "arRequest", ReplyAction="http://webapplication.odontosys.edu.pucp.pe/TipoDocumentoWA/tipoDocumento_modific" +
            "arResponse")]
        System.Threading.Tasks.Task<OdontoSysBusiness.TipoDocumentoWS.tipoDocumento_modificarResponse> tipoDocumento_modificarAsync(OdontoSysBusiness.TipoDocumentoWS.tipoDocumento_modificarRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webapplication.odontosys.edu.pucp.pe/TipoDocumentoWA/tipoDocumento_listarT" +
            "odosRequest", ReplyAction="http://webapplication.odontosys.edu.pucp.pe/TipoDocumentoWA/tipoDocumento_listarT" +
            "odosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        OdontoSysBusiness.TipoDocumentoWS.tipoDocumento_listarTodosResponse tipoDocumento_listarTodos(OdontoSysBusiness.TipoDocumentoWS.tipoDocumento_listarTodosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webapplication.odontosys.edu.pucp.pe/TipoDocumentoWA/tipoDocumento_listarT" +
            "odosRequest", ReplyAction="http://webapplication.odontosys.edu.pucp.pe/TipoDocumentoWA/tipoDocumento_listarT" +
            "odosResponse")]
        System.Threading.Tasks.Task<OdontoSysBusiness.TipoDocumentoWS.tipoDocumento_listarTodosResponse> tipoDocumento_listarTodosAsync(OdontoSysBusiness.TipoDocumentoWS.tipoDocumento_listarTodosRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webapplication.odontosys.edu.pucp.pe/")]
    public partial class tipoDocumento : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idTipoDocumentoField;
        
        private bool idTipoDocumentoFieldSpecified;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int idTipoDocumento {
            get {
                return this.idTipoDocumentoField;
            }
            set {
                this.idTipoDocumentoField = value;
                this.RaisePropertyChanged("idTipoDocumento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idTipoDocumentoSpecified {
            get {
                return this.idTipoDocumentoFieldSpecified;
            }
            set {
                this.idTipoDocumentoFieldSpecified = value;
                this.RaisePropertyChanged("idTipoDocumentoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="tipoDocumento_obtenerPorId", WrapperNamespace="http://webapplication.odontosys.edu.pucp.pe/", IsWrapped=true)]
    public partial class tipoDocumento_obtenerPorIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webapplication.odontosys.edu.pucp.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public tipoDocumento_obtenerPorIdRequest() {
        }
        
        public tipoDocumento_obtenerPorIdRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="tipoDocumento_obtenerPorIdResponse", WrapperNamespace="http://webapplication.odontosys.edu.pucp.pe/", IsWrapped=true)]
    public partial class tipoDocumento_obtenerPorIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webapplication.odontosys.edu.pucp.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public OdontoSysBusiness.TipoDocumentoWS.tipoDocumento @return;
        
        public tipoDocumento_obtenerPorIdResponse() {
        }
        
        public tipoDocumento_obtenerPorIdResponse(OdontoSysBusiness.TipoDocumentoWS.tipoDocumento @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="tipoDocumento_insertar", WrapperNamespace="http://webapplication.odontosys.edu.pucp.pe/", IsWrapped=true)]
    public partial class tipoDocumento_insertarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webapplication.odontosys.edu.pucp.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public OdontoSysBusiness.TipoDocumentoWS.tipoDocumento tipoDocumento;
        
        public tipoDocumento_insertarRequest() {
        }
        
        public tipoDocumento_insertarRequest(OdontoSysBusiness.TipoDocumentoWS.tipoDocumento tipoDocumento) {
            this.tipoDocumento = tipoDocumento;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="tipoDocumento_insertarResponse", WrapperNamespace="http://webapplication.odontosys.edu.pucp.pe/", IsWrapped=true)]
    public partial class tipoDocumento_insertarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webapplication.odontosys.edu.pucp.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public tipoDocumento_insertarResponse() {
        }
        
        public tipoDocumento_insertarResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="tipoDocumento_eliminar", WrapperNamespace="http://webapplication.odontosys.edu.pucp.pe/", IsWrapped=true)]
    public partial class tipoDocumento_eliminarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webapplication.odontosys.edu.pucp.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public OdontoSysBusiness.TipoDocumentoWS.tipoDocumento tipoDocumento;
        
        public tipoDocumento_eliminarRequest() {
        }
        
        public tipoDocumento_eliminarRequest(OdontoSysBusiness.TipoDocumentoWS.tipoDocumento tipoDocumento) {
            this.tipoDocumento = tipoDocumento;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="tipoDocumento_eliminarResponse", WrapperNamespace="http://webapplication.odontosys.edu.pucp.pe/", IsWrapped=true)]
    public partial class tipoDocumento_eliminarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webapplication.odontosys.edu.pucp.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public tipoDocumento_eliminarResponse() {
        }
        
        public tipoDocumento_eliminarResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="tipoDocumento_modificar", WrapperNamespace="http://webapplication.odontosys.edu.pucp.pe/", IsWrapped=true)]
    public partial class tipoDocumento_modificarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webapplication.odontosys.edu.pucp.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public OdontoSysBusiness.TipoDocumentoWS.tipoDocumento tipoDocumento;
        
        public tipoDocumento_modificarRequest() {
        }
        
        public tipoDocumento_modificarRequest(OdontoSysBusiness.TipoDocumentoWS.tipoDocumento tipoDocumento) {
            this.tipoDocumento = tipoDocumento;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="tipoDocumento_modificarResponse", WrapperNamespace="http://webapplication.odontosys.edu.pucp.pe/", IsWrapped=true)]
    public partial class tipoDocumento_modificarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webapplication.odontosys.edu.pucp.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public tipoDocumento_modificarResponse() {
        }
        
        public tipoDocumento_modificarResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="tipoDocumento_listarTodos", WrapperNamespace="http://webapplication.odontosys.edu.pucp.pe/", IsWrapped=true)]
    public partial class tipoDocumento_listarTodosRequest {
        
        public tipoDocumento_listarTodosRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="tipoDocumento_listarTodosResponse", WrapperNamespace="http://webapplication.odontosys.edu.pucp.pe/", IsWrapped=true)]
    public partial class tipoDocumento_listarTodosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webapplication.odontosys.edu.pucp.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public OdontoSysBusiness.TipoDocumentoWS.tipoDocumento[] @return;
        
        public tipoDocumento_listarTodosResponse() {
        }
        
        public tipoDocumento_listarTodosResponse(OdontoSysBusiness.TipoDocumentoWS.tipoDocumento[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TipoDocumentoWAChannel : OdontoSysBusiness.TipoDocumentoWS.TipoDocumentoWA, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TipoDocumentoWAClient : System.ServiceModel.ClientBase<OdontoSysBusiness.TipoDocumentoWS.TipoDocumentoWA>, OdontoSysBusiness.TipoDocumentoWS.TipoDocumentoWA {
        
        public TipoDocumentoWAClient() {
        }
        
        public TipoDocumentoWAClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TipoDocumentoWAClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TipoDocumentoWAClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TipoDocumentoWAClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OdontoSysBusiness.TipoDocumentoWS.tipoDocumento_obtenerPorIdResponse OdontoSysBusiness.TipoDocumentoWS.TipoDocumentoWA.tipoDocumento_obtenerPorId(OdontoSysBusiness.TipoDocumentoWS.tipoDocumento_obtenerPorIdRequest request) {
            return base.Channel.tipoDocumento_obtenerPorId(request);
        }
        
        public OdontoSysBusiness.TipoDocumentoWS.tipoDocumento tipoDocumento_obtenerPorId(int id) {
            OdontoSysBusiness.TipoDocumentoWS.tipoDocumento_obtenerPorIdRequest inValue = new OdontoSysBusiness.TipoDocumentoWS.tipoDocumento_obtenerPorIdRequest();
            inValue.id = id;
            OdontoSysBusiness.TipoDocumentoWS.tipoDocumento_obtenerPorIdResponse retVal = ((OdontoSysBusiness.TipoDocumentoWS.TipoDocumentoWA)(this)).tipoDocumento_obtenerPorId(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OdontoSysBusiness.TipoDocumentoWS.tipoDocumento_obtenerPorIdResponse> OdontoSysBusiness.TipoDocumentoWS.TipoDocumentoWA.tipoDocumento_obtenerPorIdAsync(OdontoSysBusiness.TipoDocumentoWS.tipoDocumento_obtenerPorIdRequest request) {
            return base.Channel.tipoDocumento_obtenerPorIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<OdontoSysBusiness.TipoDocumentoWS.tipoDocumento_obtenerPorIdResponse> tipoDocumento_obtenerPorIdAsync(int id) {
            OdontoSysBusiness.TipoDocumentoWS.tipoDocumento_obtenerPorIdRequest inValue = new OdontoSysBusiness.TipoDocumentoWS.tipoDocumento_obtenerPorIdRequest();
            inValue.id = id;
            return ((OdontoSysBusiness.TipoDocumentoWS.TipoDocumentoWA)(this)).tipoDocumento_obtenerPorIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OdontoSysBusiness.TipoDocumentoWS.tipoDocumento_insertarResponse OdontoSysBusiness.TipoDocumentoWS.TipoDocumentoWA.tipoDocumento_insertar(OdontoSysBusiness.TipoDocumentoWS.tipoDocumento_insertarRequest request) {
            return base.Channel.tipoDocumento_insertar(request);
        }
        
        public int tipoDocumento_insertar(OdontoSysBusiness.TipoDocumentoWS.tipoDocumento tipoDocumento) {
            OdontoSysBusiness.TipoDocumentoWS.tipoDocumento_insertarRequest inValue = new OdontoSysBusiness.TipoDocumentoWS.tipoDocumento_insertarRequest();
            inValue.tipoDocumento = tipoDocumento;
            OdontoSysBusiness.TipoDocumentoWS.tipoDocumento_insertarResponse retVal = ((OdontoSysBusiness.TipoDocumentoWS.TipoDocumentoWA)(this)).tipoDocumento_insertar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OdontoSysBusiness.TipoDocumentoWS.tipoDocumento_insertarResponse> OdontoSysBusiness.TipoDocumentoWS.TipoDocumentoWA.tipoDocumento_insertarAsync(OdontoSysBusiness.TipoDocumentoWS.tipoDocumento_insertarRequest request) {
            return base.Channel.tipoDocumento_insertarAsync(request);
        }
        
        public System.Threading.Tasks.Task<OdontoSysBusiness.TipoDocumentoWS.tipoDocumento_insertarResponse> tipoDocumento_insertarAsync(OdontoSysBusiness.TipoDocumentoWS.tipoDocumento tipoDocumento) {
            OdontoSysBusiness.TipoDocumentoWS.tipoDocumento_insertarRequest inValue = new OdontoSysBusiness.TipoDocumentoWS.tipoDocumento_insertarRequest();
            inValue.tipoDocumento = tipoDocumento;
            return ((OdontoSysBusiness.TipoDocumentoWS.TipoDocumentoWA)(this)).tipoDocumento_insertarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OdontoSysBusiness.TipoDocumentoWS.tipoDocumento_eliminarResponse OdontoSysBusiness.TipoDocumentoWS.TipoDocumentoWA.tipoDocumento_eliminar(OdontoSysBusiness.TipoDocumentoWS.tipoDocumento_eliminarRequest request) {
            return base.Channel.tipoDocumento_eliminar(request);
        }
        
        public int tipoDocumento_eliminar(OdontoSysBusiness.TipoDocumentoWS.tipoDocumento tipoDocumento) {
            OdontoSysBusiness.TipoDocumentoWS.tipoDocumento_eliminarRequest inValue = new OdontoSysBusiness.TipoDocumentoWS.tipoDocumento_eliminarRequest();
            inValue.tipoDocumento = tipoDocumento;
            OdontoSysBusiness.TipoDocumentoWS.tipoDocumento_eliminarResponse retVal = ((OdontoSysBusiness.TipoDocumentoWS.TipoDocumentoWA)(this)).tipoDocumento_eliminar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OdontoSysBusiness.TipoDocumentoWS.tipoDocumento_eliminarResponse> OdontoSysBusiness.TipoDocumentoWS.TipoDocumentoWA.tipoDocumento_eliminarAsync(OdontoSysBusiness.TipoDocumentoWS.tipoDocumento_eliminarRequest request) {
            return base.Channel.tipoDocumento_eliminarAsync(request);
        }
        
        public System.Threading.Tasks.Task<OdontoSysBusiness.TipoDocumentoWS.tipoDocumento_eliminarResponse> tipoDocumento_eliminarAsync(OdontoSysBusiness.TipoDocumentoWS.tipoDocumento tipoDocumento) {
            OdontoSysBusiness.TipoDocumentoWS.tipoDocumento_eliminarRequest inValue = new OdontoSysBusiness.TipoDocumentoWS.tipoDocumento_eliminarRequest();
            inValue.tipoDocumento = tipoDocumento;
            return ((OdontoSysBusiness.TipoDocumentoWS.TipoDocumentoWA)(this)).tipoDocumento_eliminarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OdontoSysBusiness.TipoDocumentoWS.tipoDocumento_modificarResponse OdontoSysBusiness.TipoDocumentoWS.TipoDocumentoWA.tipoDocumento_modificar(OdontoSysBusiness.TipoDocumentoWS.tipoDocumento_modificarRequest request) {
            return base.Channel.tipoDocumento_modificar(request);
        }
        
        public int tipoDocumento_modificar(OdontoSysBusiness.TipoDocumentoWS.tipoDocumento tipoDocumento) {
            OdontoSysBusiness.TipoDocumentoWS.tipoDocumento_modificarRequest inValue = new OdontoSysBusiness.TipoDocumentoWS.tipoDocumento_modificarRequest();
            inValue.tipoDocumento = tipoDocumento;
            OdontoSysBusiness.TipoDocumentoWS.tipoDocumento_modificarResponse retVal = ((OdontoSysBusiness.TipoDocumentoWS.TipoDocumentoWA)(this)).tipoDocumento_modificar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OdontoSysBusiness.TipoDocumentoWS.tipoDocumento_modificarResponse> OdontoSysBusiness.TipoDocumentoWS.TipoDocumentoWA.tipoDocumento_modificarAsync(OdontoSysBusiness.TipoDocumentoWS.tipoDocumento_modificarRequest request) {
            return base.Channel.tipoDocumento_modificarAsync(request);
        }
        
        public System.Threading.Tasks.Task<OdontoSysBusiness.TipoDocumentoWS.tipoDocumento_modificarResponse> tipoDocumento_modificarAsync(OdontoSysBusiness.TipoDocumentoWS.tipoDocumento tipoDocumento) {
            OdontoSysBusiness.TipoDocumentoWS.tipoDocumento_modificarRequest inValue = new OdontoSysBusiness.TipoDocumentoWS.tipoDocumento_modificarRequest();
            inValue.tipoDocumento = tipoDocumento;
            return ((OdontoSysBusiness.TipoDocumentoWS.TipoDocumentoWA)(this)).tipoDocumento_modificarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OdontoSysBusiness.TipoDocumentoWS.tipoDocumento_listarTodosResponse OdontoSysBusiness.TipoDocumentoWS.TipoDocumentoWA.tipoDocumento_listarTodos(OdontoSysBusiness.TipoDocumentoWS.tipoDocumento_listarTodosRequest request) {
            return base.Channel.tipoDocumento_listarTodos(request);
        }
        
        public OdontoSysBusiness.TipoDocumentoWS.tipoDocumento[] tipoDocumento_listarTodos() {
            OdontoSysBusiness.TipoDocumentoWS.tipoDocumento_listarTodosRequest inValue = new OdontoSysBusiness.TipoDocumentoWS.tipoDocumento_listarTodosRequest();
            OdontoSysBusiness.TipoDocumentoWS.tipoDocumento_listarTodosResponse retVal = ((OdontoSysBusiness.TipoDocumentoWS.TipoDocumentoWA)(this)).tipoDocumento_listarTodos(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OdontoSysBusiness.TipoDocumentoWS.tipoDocumento_listarTodosResponse> OdontoSysBusiness.TipoDocumentoWS.TipoDocumentoWA.tipoDocumento_listarTodosAsync(OdontoSysBusiness.TipoDocumentoWS.tipoDocumento_listarTodosRequest request) {
            return base.Channel.tipoDocumento_listarTodosAsync(request);
        }
        
        public System.Threading.Tasks.Task<OdontoSysBusiness.TipoDocumentoWS.tipoDocumento_listarTodosResponse> tipoDocumento_listarTodosAsync() {
            OdontoSysBusiness.TipoDocumentoWS.tipoDocumento_listarTodosRequest inValue = new OdontoSysBusiness.TipoDocumentoWS.tipoDocumento_listarTodosRequest();
            return ((OdontoSysBusiness.TipoDocumentoWS.TipoDocumentoWA)(this)).tipoDocumento_listarTodosAsync(inValue);
        }
    }
}
