//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OdontoSysBusiness.odontologoWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://wa.odontosys.com/", ConfigurationName="odontologoWS.Odontologos")]
    public interface Odontologos {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://wa.odontosys.com/Odontologos/eliminarOdontologoRequest", ReplyAction="http://wa.odontosys.com/Odontologos/eliminarOdontologoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        OdontoSysBusiness.odontologoWS.eliminarOdontologoResponse eliminarOdontologo(OdontoSysBusiness.odontologoWS.eliminarOdontologoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wa.odontosys.com/Odontologos/eliminarOdontologoRequest", ReplyAction="http://wa.odontosys.com/Odontologos/eliminarOdontologoResponse")]
        System.Threading.Tasks.Task<OdontoSysBusiness.odontologoWS.eliminarOdontologoResponse> eliminarOdontologoAsync(OdontoSysBusiness.odontologoWS.eliminarOdontologoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://wa.odontosys.com/Odontologos/od_obtenerPorIDRequest", ReplyAction="http://wa.odontosys.com/Odontologos/od_obtenerPorIDResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        OdontoSysBusiness.odontologoWS.od_obtenerPorIDResponse od_obtenerPorID(OdontoSysBusiness.odontologoWS.od_obtenerPorIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wa.odontosys.com/Odontologos/od_obtenerPorIDRequest", ReplyAction="http://wa.odontosys.com/Odontologos/od_obtenerPorIDResponse")]
        System.Threading.Tasks.Task<OdontoSysBusiness.odontologoWS.od_obtenerPorIDResponse> od_obtenerPorIDAsync(OdontoSysBusiness.odontologoWS.od_obtenerPorIDRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://wa.odontosys.com/Odontologos/insertarOdontologoRequest", ReplyAction="http://wa.odontosys.com/Odontologos/insertarOdontologoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        OdontoSysBusiness.odontologoWS.insertarOdontologoResponse insertarOdontologo(OdontoSysBusiness.odontologoWS.insertarOdontologoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wa.odontosys.com/Odontologos/insertarOdontologoRequest", ReplyAction="http://wa.odontosys.com/Odontologos/insertarOdontologoResponse")]
        System.Threading.Tasks.Task<OdontoSysBusiness.odontologoWS.insertarOdontologoResponse> insertarOdontologoAsync(OdontoSysBusiness.odontologoWS.insertarOdontologoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://wa.odontosys.com/Odontologos/modificarOdontologoRequest", ReplyAction="http://wa.odontosys.com/Odontologos/modificarOdontologoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        OdontoSysBusiness.odontologoWS.modificarOdontologoResponse modificarOdontologo(OdontoSysBusiness.odontologoWS.modificarOdontologoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wa.odontosys.com/Odontologos/modificarOdontologoRequest", ReplyAction="http://wa.odontosys.com/Odontologos/modificarOdontologoResponse")]
        System.Threading.Tasks.Task<OdontoSysBusiness.odontologoWS.modificarOdontologoResponse> modificarOdontologoAsync(OdontoSysBusiness.odontologoWS.modificarOdontologoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://wa.odontosys.com/Odontologos/listarPorEspecialidadRequest", ReplyAction="http://wa.odontosys.com/Odontologos/listarPorEspecialidadResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        OdontoSysBusiness.odontologoWS.listarPorEspecialidadResponse listarPorEspecialidad(OdontoSysBusiness.odontologoWS.listarPorEspecialidadRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wa.odontosys.com/Odontologos/listarPorEspecialidadRequest", ReplyAction="http://wa.odontosys.com/Odontologos/listarPorEspecialidadResponse")]
        System.Threading.Tasks.Task<OdontoSysBusiness.odontologoWS.listarPorEspecialidadResponse> listarPorEspecialidadAsync(OdontoSysBusiness.odontologoWS.listarPorEspecialidadRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://wa.odontosys.com/Odontologos/od_buscarPorUsuarioRequest", ReplyAction="http://wa.odontosys.com/Odontologos/od_buscarPorUsuarioResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        OdontoSysBusiness.odontologoWS.od_buscarPorUsuarioResponse od_buscarPorUsuario(OdontoSysBusiness.odontologoWS.od_buscarPorUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wa.odontosys.com/Odontologos/od_buscarPorUsuarioRequest", ReplyAction="http://wa.odontosys.com/Odontologos/od_buscarPorUsuarioResponse")]
        System.Threading.Tasks.Task<OdontoSysBusiness.odontologoWS.od_buscarPorUsuarioResponse> od_buscarPorUsuarioAsync(OdontoSysBusiness.odontologoWS.od_buscarPorUsuarioRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://wa.odontosys.com/Odontologos/od_listarOdontologosRequest", ReplyAction="http://wa.odontosys.com/Odontologos/od_listarOdontologosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        OdontoSysBusiness.odontologoWS.od_listarOdontologosResponse od_listarOdontologos(OdontoSysBusiness.odontologoWS.od_listarOdontologosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wa.odontosys.com/Odontologos/od_listarOdontologosRequest", ReplyAction="http://wa.odontosys.com/Odontologos/od_listarOdontologosResponse")]
        System.Threading.Tasks.Task<OdontoSysBusiness.odontologoWS.od_listarOdontologosResponse> od_listarOdontologosAsync(OdontoSysBusiness.odontologoWS.od_listarOdontologosRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wa.odontosys.com/")]
    public partial class odontologo : persona {
        
        private cita[] citasField;
        
        private sala consultorioField;
        
        private especialidad especialidadField;
        
        private int idOdontologoField;
        
        private double puntuacionPromedioField;
        
        private turno[] turnosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("citas", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public cita[] citas {
            get {
                return this.citasField;
            }
            set {
                this.citasField = value;
                this.RaisePropertyChanged("citas");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public sala consultorio {
            get {
                return this.consultorioField;
            }
            set {
                this.consultorioField = value;
                this.RaisePropertyChanged("consultorio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public especialidad especialidad {
            get {
                return this.especialidadField;
            }
            set {
                this.especialidadField = value;
                this.RaisePropertyChanged("especialidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int idOdontologo {
            get {
                return this.idOdontologoField;
            }
            set {
                this.idOdontologoField = value;
                this.RaisePropertyChanged("idOdontologo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public double puntuacionPromedio {
            get {
                return this.puntuacionPromedioField;
            }
            set {
                this.puntuacionPromedioField = value;
                this.RaisePropertyChanged("puntuacionPromedio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("turnos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public turno[] turnos {
            get {
                return this.turnosField;
            }
            set {
                this.turnosField = value;
                this.RaisePropertyChanged("turnos");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wa.odontosys.com/")]
    public partial class cita : object, System.ComponentModel.INotifyPropertyChanged {
        
        private comprobante comprobanteField;
        
        private estadoCita estadoField;
        
        private bool estadoFieldSpecified;
        
        private localDate fechaField;
        
        private localTime horaInicioField;
        
        private int idCitaField;
        
        private odontologo odontologoField;
        
        private paciente pacienteField;
        
        private double puntuacionField;
        
        private recepcionista recepcionistaField;
        
        private detalleTratamiento[] tratamientosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public comprobante comprobante {
            get {
                return this.comprobanteField;
            }
            set {
                this.comprobanteField = value;
                this.RaisePropertyChanged("comprobante");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public estadoCita estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool estadoSpecified {
            get {
                return this.estadoFieldSpecified;
            }
            set {
                this.estadoFieldSpecified = value;
                this.RaisePropertyChanged("estadoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public localDate fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
                this.RaisePropertyChanged("fecha");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public localTime horaInicio {
            get {
                return this.horaInicioField;
            }
            set {
                this.horaInicioField = value;
                this.RaisePropertyChanged("horaInicio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int idCita {
            get {
                return this.idCitaField;
            }
            set {
                this.idCitaField = value;
                this.RaisePropertyChanged("idCita");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public odontologo odontologo {
            get {
                return this.odontologoField;
            }
            set {
                this.odontologoField = value;
                this.RaisePropertyChanged("odontologo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public paciente paciente {
            get {
                return this.pacienteField;
            }
            set {
                this.pacienteField = value;
                this.RaisePropertyChanged("paciente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public double puntuacion {
            get {
                return this.puntuacionField;
            }
            set {
                this.puntuacionField = value;
                this.RaisePropertyChanged("puntuacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public recepcionista recepcionista {
            get {
                return this.recepcionistaField;
            }
            set {
                this.recepcionistaField = value;
                this.RaisePropertyChanged("recepcionista");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("tratamientos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=9)]
        public detalleTratamiento[] tratamientos {
            get {
                return this.tratamientosField;
            }
            set {
                this.tratamientosField = value;
                this.RaisePropertyChanged("tratamientos");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wa.odontosys.com/")]
    public partial class comprobante : object, System.ComponentModel.INotifyPropertyChanged {
        
        private localDate fechaEmisionField;
        
        private localTime horaEmisionField;
        
        private int idComprobanteField;
        
        private metodoPago metodoDePagoField;
        
        private double totalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public localDate fechaEmision {
            get {
                return this.fechaEmisionField;
            }
            set {
                this.fechaEmisionField = value;
                this.RaisePropertyChanged("fechaEmision");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public localTime horaEmision {
            get {
                return this.horaEmisionField;
            }
            set {
                this.horaEmisionField = value;
                this.RaisePropertyChanged("horaEmision");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idComprobante {
            get {
                return this.idComprobanteField;
            }
            set {
                this.idComprobanteField = value;
                this.RaisePropertyChanged("idComprobante");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public metodoPago metodoDePago {
            get {
                return this.metodoDePagoField;
            }
            set {
                this.metodoDePagoField = value;
                this.RaisePropertyChanged("metodoDePago");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public double total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
                this.RaisePropertyChanged("total");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wa.odontosys.com/")]
    public partial class localDate : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wa.odontosys.com/")]
    public partial class turno : object, System.ComponentModel.INotifyPropertyChanged {
        
        private diaSemana diaSemanaField;
        
        private bool diaSemanaFieldSpecified;
        
        private localTime horaFinField;
        
        private localTime horaInicioField;
        
        private int idTurnoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public diaSemana diaSemana {
            get {
                return this.diaSemanaField;
            }
            set {
                this.diaSemanaField = value;
                this.RaisePropertyChanged("diaSemana");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool diaSemanaSpecified {
            get {
                return this.diaSemanaFieldSpecified;
            }
            set {
                this.diaSemanaFieldSpecified = value;
                this.RaisePropertyChanged("diaSemanaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public localTime horaFin {
            get {
                return this.horaFinField;
            }
            set {
                this.horaFinField = value;
                this.RaisePropertyChanged("horaFin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public localTime horaInicio {
            get {
                return this.horaInicioField;
            }
            set {
                this.horaInicioField = value;
                this.RaisePropertyChanged("horaInicio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int idTurno {
            get {
                return this.idTurnoField;
            }
            set {
                this.idTurnoField = value;
                this.RaisePropertyChanged("idTurno");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wa.odontosys.com/")]
    public enum diaSemana {
        
        /// <remarks/>
        MONDAY,
        
        /// <remarks/>
        TUESDAY,
        
        /// <remarks/>
        WEDNESDAY,
        
        /// <remarks/>
        THURSDAY,
        
        /// <remarks/>
        FRIDAY,
        
        /// <remarks/>
        SATURDAY,
        
        /// <remarks/>
        SUNDAY,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wa.odontosys.com/")]
    public partial class localTime : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wa.odontosys.com/")]
    public partial class sala : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idSalaField;
        
        private string numeroField;
        
        private int pisoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int idSala {
            get {
                return this.idSalaField;
            }
            set {
                this.idSalaField = value;
                this.RaisePropertyChanged("idSala");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
                this.RaisePropertyChanged("numero");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int piso {
            get {
                return this.pisoField;
            }
            set {
                this.pisoField = value;
                this.RaisePropertyChanged("piso");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wa.odontosys.com/")]
    public partial class especialidad : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idEspecialidadField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int idEspecialidad {
            get {
                return this.idEspecialidadField;
            }
            set {
                this.idEspecialidadField = value;
                this.RaisePropertyChanged("idEspecialidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wa.odontosys.com/")]
    public partial class tratamiento : object, System.ComponentModel.INotifyPropertyChanged {
        
        private double costoField;
        
        private string descripcionField;
        
        private especialidad especialidadField;
        
        private int idTratamientoField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public double costo {
            get {
                return this.costoField;
            }
            set {
                this.costoField = value;
                this.RaisePropertyChanged("costo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public especialidad especialidad {
            get {
                return this.especialidadField;
            }
            set {
                this.especialidadField = value;
                this.RaisePropertyChanged("especialidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int idTratamiento {
            get {
                return this.idTratamientoField;
            }
            set {
                this.idTratamientoField = value;
                this.RaisePropertyChanged("idTratamiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wa.odontosys.com/")]
    public partial class detalleTratamiento : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int cantidadField;
        
        private int idCitaField;
        
        private double subtotalField;
        
        private tratamiento tratamientoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int cantidad {
            get {
                return this.cantidadField;
            }
            set {
                this.cantidadField = value;
                this.RaisePropertyChanged("cantidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int idCita {
            get {
                return this.idCitaField;
            }
            set {
                this.idCitaField = value;
                this.RaisePropertyChanged("idCita");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public double subtotal {
            get {
                return this.subtotalField;
            }
            set {
                this.subtotalField = value;
                this.RaisePropertyChanged("subtotal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public tratamiento tratamiento {
            get {
                return this.tratamientoField;
            }
            set {
                this.tratamientoField = value;
                this.RaisePropertyChanged("tratamiento");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wa.odontosys.com/")]
    public partial class metodoPago : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idMetodoPagoField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int idMetodoPago {
            get {
                return this.idMetodoPagoField;
            }
            set {
                this.idMetodoPagoField = value;
                this.RaisePropertyChanged("idMetodoPago");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(recepcionista))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(paciente))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(odontologo))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wa.odontosys.com/")]
    public abstract partial class persona : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string apellidosField;
        
        private string contrasenhaField;
        
        private string correoField;
        
        private string nombreField;
        
        private string nombreUsuarioField;
        
        private string numeroDocumentoField;
        
        private string telefonoField;
        
        private tipoDocumento tipoDocumentoField;
        
        private bool tipoDocumentoFieldSpecified;
        
        private tipoUsuario tipoUsuarioField;
        
        private bool tipoUsuarioFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string apellidos {
            get {
                return this.apellidosField;
            }
            set {
                this.apellidosField = value;
                this.RaisePropertyChanged("apellidos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string contrasenha {
            get {
                return this.contrasenhaField;
            }
            set {
                this.contrasenhaField = value;
                this.RaisePropertyChanged("contrasenha");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string correo {
            get {
                return this.correoField;
            }
            set {
                this.correoField = value;
                this.RaisePropertyChanged("correo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string nombreUsuario {
            get {
                return this.nombreUsuarioField;
            }
            set {
                this.nombreUsuarioField = value;
                this.RaisePropertyChanged("nombreUsuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string numeroDocumento {
            get {
                return this.numeroDocumentoField;
            }
            set {
                this.numeroDocumentoField = value;
                this.RaisePropertyChanged("numeroDocumento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("telefono");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public tipoDocumento tipoDocumento {
            get {
                return this.tipoDocumentoField;
            }
            set {
                this.tipoDocumentoField = value;
                this.RaisePropertyChanged("tipoDocumento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipoDocumentoSpecified {
            get {
                return this.tipoDocumentoFieldSpecified;
            }
            set {
                this.tipoDocumentoFieldSpecified = value;
                this.RaisePropertyChanged("tipoDocumentoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public tipoUsuario tipoUsuario {
            get {
                return this.tipoUsuarioField;
            }
            set {
                this.tipoUsuarioField = value;
                this.RaisePropertyChanged("tipoUsuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipoUsuarioSpecified {
            get {
                return this.tipoUsuarioFieldSpecified;
            }
            set {
                this.tipoUsuarioFieldSpecified = value;
                this.RaisePropertyChanged("tipoUsuarioSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wa.odontosys.com/")]
    public enum tipoDocumento {
        
        /// <remarks/>
        DNI,
        
        /// <remarks/>
        CARNE_DE_EXTRANJERIA,
        
        /// <remarks/>
        PASAPORTE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wa.odontosys.com/")]
    public enum tipoUsuario {
        
        /// <remarks/>
        PLACEHOLDER,
        
        /// <remarks/>
        PACIENTE,
        
        /// <remarks/>
        ODONTOLOGO,
        
        /// <remarks/>
        RECEPCIONISTA,
        
        /// <remarks/>
        ADMINISTRADOR,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wa.odontosys.com/")]
    public partial class recepcionista : persona {
        
        private int idRecepcionistaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int idRecepcionista {
            get {
                return this.idRecepcionistaField;
            }
            set {
                this.idRecepcionistaField = value;
                this.RaisePropertyChanged("idRecepcionista");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wa.odontosys.com/")]
    public partial class paciente : persona {
        
        private cita[] citasField;
        
        private int idPacienteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("citas", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public cita[] citas {
            get {
                return this.citasField;
            }
            set {
                this.citasField = value;
                this.RaisePropertyChanged("citas");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int idPaciente {
            get {
                return this.idPacienteField;
            }
            set {
                this.idPacienteField = value;
                this.RaisePropertyChanged("idPaciente");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wa.odontosys.com/")]
    public enum estadoCita {
        
        /// <remarks/>
        RESERVADA,
        
        /// <remarks/>
        ATENDIDA,
        
        /// <remarks/>
        CANCELADA,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarOdontologo", WrapperNamespace="http://wa.odontosys.com/", IsWrapped=true)]
    public partial class eliminarOdontologoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wa.odontosys.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public OdontoSysBusiness.odontologoWS.odontologo odontologo;
        
        public eliminarOdontologoRequest() {
        }
        
        public eliminarOdontologoRequest(OdontoSysBusiness.odontologoWS.odontologo odontologo) {
            this.odontologo = odontologo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarOdontologoResponse", WrapperNamespace="http://wa.odontosys.com/", IsWrapped=true)]
    public partial class eliminarOdontologoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wa.odontosys.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarOdontologoResponse() {
        }
        
        public eliminarOdontologoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="od_obtenerPorID", WrapperNamespace="http://wa.odontosys.com/", IsWrapped=true)]
    public partial class od_obtenerPorIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wa.odontosys.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int odontologoId;
        
        public od_obtenerPorIDRequest() {
        }
        
        public od_obtenerPorIDRequest(int odontologoId) {
            this.odontologoId = odontologoId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="od_obtenerPorIDResponse", WrapperNamespace="http://wa.odontosys.com/", IsWrapped=true)]
    public partial class od_obtenerPorIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wa.odontosys.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public OdontoSysBusiness.odontologoWS.odontologo @return;
        
        public od_obtenerPorIDResponse() {
        }
        
        public od_obtenerPorIDResponse(OdontoSysBusiness.odontologoWS.odontologo @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarOdontologo", WrapperNamespace="http://wa.odontosys.com/", IsWrapped=true)]
    public partial class insertarOdontologoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wa.odontosys.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public OdontoSysBusiness.odontologoWS.odontologo odontologo;
        
        public insertarOdontologoRequest() {
        }
        
        public insertarOdontologoRequest(OdontoSysBusiness.odontologoWS.odontologo odontologo) {
            this.odontologo = odontologo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarOdontologoResponse", WrapperNamespace="http://wa.odontosys.com/", IsWrapped=true)]
    public partial class insertarOdontologoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wa.odontosys.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarOdontologoResponse() {
        }
        
        public insertarOdontologoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarOdontologo", WrapperNamespace="http://wa.odontosys.com/", IsWrapped=true)]
    public partial class modificarOdontologoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wa.odontosys.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public OdontoSysBusiness.odontologoWS.odontologo odontologo;
        
        public modificarOdontologoRequest() {
        }
        
        public modificarOdontologoRequest(OdontoSysBusiness.odontologoWS.odontologo odontologo) {
            this.odontologo = odontologo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarOdontologoResponse", WrapperNamespace="http://wa.odontosys.com/", IsWrapped=true)]
    public partial class modificarOdontologoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wa.odontosys.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarOdontologoResponse() {
        }
        
        public modificarOdontologoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarPorEspecialidad", WrapperNamespace="http://wa.odontosys.com/", IsWrapped=true)]
    public partial class listarPorEspecialidadRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wa.odontosys.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public OdontoSysBusiness.odontologoWS.especialidad especialidad;
        
        public listarPorEspecialidadRequest() {
        }
        
        public listarPorEspecialidadRequest(OdontoSysBusiness.odontologoWS.especialidad especialidad) {
            this.especialidad = especialidad;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarPorEspecialidadResponse", WrapperNamespace="http://wa.odontosys.com/", IsWrapped=true)]
    public partial class listarPorEspecialidadResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wa.odontosys.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public OdontoSysBusiness.odontologoWS.odontologo[] @return;
        
        public listarPorEspecialidadResponse() {
        }
        
        public listarPorEspecialidadResponse(OdontoSysBusiness.odontologoWS.odontologo[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="od_buscarPorUsuario", WrapperNamespace="http://wa.odontosys.com/", IsWrapped=true)]
    public partial class od_buscarPorUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wa.odontosys.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string odontologoUsuario;
        
        public od_buscarPorUsuarioRequest() {
        }
        
        public od_buscarPorUsuarioRequest(string odontologoUsuario) {
            this.odontologoUsuario = odontologoUsuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="od_buscarPorUsuarioResponse", WrapperNamespace="http://wa.odontosys.com/", IsWrapped=true)]
    public partial class od_buscarPorUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wa.odontosys.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public OdontoSysBusiness.odontologoWS.odontologo @return;
        
        public od_buscarPorUsuarioResponse() {
        }
        
        public od_buscarPorUsuarioResponse(OdontoSysBusiness.odontologoWS.odontologo @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="od_listarOdontologos", WrapperNamespace="http://wa.odontosys.com/", IsWrapped=true)]
    public partial class od_listarOdontologosRequest {
        
        public od_listarOdontologosRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="od_listarOdontologosResponse", WrapperNamespace="http://wa.odontosys.com/", IsWrapped=true)]
    public partial class od_listarOdontologosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wa.odontosys.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public OdontoSysBusiness.odontologoWS.odontologo[] @return;
        
        public od_listarOdontologosResponse() {
        }
        
        public od_listarOdontologosResponse(OdontoSysBusiness.odontologoWS.odontologo[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface OdontologosChannel : OdontoSysBusiness.odontologoWS.Odontologos, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OdontologosClient : System.ServiceModel.ClientBase<OdontoSysBusiness.odontologoWS.Odontologos>, OdontoSysBusiness.odontologoWS.Odontologos {
        
        public OdontologosClient() {
        }
        
        public OdontologosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OdontologosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OdontologosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OdontologosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OdontoSysBusiness.odontologoWS.eliminarOdontologoResponse OdontoSysBusiness.odontologoWS.Odontologos.eliminarOdontologo(OdontoSysBusiness.odontologoWS.eliminarOdontologoRequest request) {
            return base.Channel.eliminarOdontologo(request);
        }
        
        public int eliminarOdontologo(OdontoSysBusiness.odontologoWS.odontologo odontologo) {
            OdontoSysBusiness.odontologoWS.eliminarOdontologoRequest inValue = new OdontoSysBusiness.odontologoWS.eliminarOdontologoRequest();
            inValue.odontologo = odontologo;
            OdontoSysBusiness.odontologoWS.eliminarOdontologoResponse retVal = ((OdontoSysBusiness.odontologoWS.Odontologos)(this)).eliminarOdontologo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OdontoSysBusiness.odontologoWS.eliminarOdontologoResponse> OdontoSysBusiness.odontologoWS.Odontologos.eliminarOdontologoAsync(OdontoSysBusiness.odontologoWS.eliminarOdontologoRequest request) {
            return base.Channel.eliminarOdontologoAsync(request);
        }
        
        public System.Threading.Tasks.Task<OdontoSysBusiness.odontologoWS.eliminarOdontologoResponse> eliminarOdontologoAsync(OdontoSysBusiness.odontologoWS.odontologo odontologo) {
            OdontoSysBusiness.odontologoWS.eliminarOdontologoRequest inValue = new OdontoSysBusiness.odontologoWS.eliminarOdontologoRequest();
            inValue.odontologo = odontologo;
            return ((OdontoSysBusiness.odontologoWS.Odontologos)(this)).eliminarOdontologoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OdontoSysBusiness.odontologoWS.od_obtenerPorIDResponse OdontoSysBusiness.odontologoWS.Odontologos.od_obtenerPorID(OdontoSysBusiness.odontologoWS.od_obtenerPorIDRequest request) {
            return base.Channel.od_obtenerPorID(request);
        }
        
        public OdontoSysBusiness.odontologoWS.odontologo od_obtenerPorID(int odontologoId) {
            OdontoSysBusiness.odontologoWS.od_obtenerPorIDRequest inValue = new OdontoSysBusiness.odontologoWS.od_obtenerPorIDRequest();
            inValue.odontologoId = odontologoId;
            OdontoSysBusiness.odontologoWS.od_obtenerPorIDResponse retVal = ((OdontoSysBusiness.odontologoWS.Odontologos)(this)).od_obtenerPorID(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OdontoSysBusiness.odontologoWS.od_obtenerPorIDResponse> OdontoSysBusiness.odontologoWS.Odontologos.od_obtenerPorIDAsync(OdontoSysBusiness.odontologoWS.od_obtenerPorIDRequest request) {
            return base.Channel.od_obtenerPorIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<OdontoSysBusiness.odontologoWS.od_obtenerPorIDResponse> od_obtenerPorIDAsync(int odontologoId) {
            OdontoSysBusiness.odontologoWS.od_obtenerPorIDRequest inValue = new OdontoSysBusiness.odontologoWS.od_obtenerPorIDRequest();
            inValue.odontologoId = odontologoId;
            return ((OdontoSysBusiness.odontologoWS.Odontologos)(this)).od_obtenerPorIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OdontoSysBusiness.odontologoWS.insertarOdontologoResponse OdontoSysBusiness.odontologoWS.Odontologos.insertarOdontologo(OdontoSysBusiness.odontologoWS.insertarOdontologoRequest request) {
            return base.Channel.insertarOdontologo(request);
        }
        
        public int insertarOdontologo(OdontoSysBusiness.odontologoWS.odontologo odontologo) {
            OdontoSysBusiness.odontologoWS.insertarOdontologoRequest inValue = new OdontoSysBusiness.odontologoWS.insertarOdontologoRequest();
            inValue.odontologo = odontologo;
            OdontoSysBusiness.odontologoWS.insertarOdontologoResponse retVal = ((OdontoSysBusiness.odontologoWS.Odontologos)(this)).insertarOdontologo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OdontoSysBusiness.odontologoWS.insertarOdontologoResponse> OdontoSysBusiness.odontologoWS.Odontologos.insertarOdontologoAsync(OdontoSysBusiness.odontologoWS.insertarOdontologoRequest request) {
            return base.Channel.insertarOdontologoAsync(request);
        }
        
        public System.Threading.Tasks.Task<OdontoSysBusiness.odontologoWS.insertarOdontologoResponse> insertarOdontologoAsync(OdontoSysBusiness.odontologoWS.odontologo odontologo) {
            OdontoSysBusiness.odontologoWS.insertarOdontologoRequest inValue = new OdontoSysBusiness.odontologoWS.insertarOdontologoRequest();
            inValue.odontologo = odontologo;
            return ((OdontoSysBusiness.odontologoWS.Odontologos)(this)).insertarOdontologoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OdontoSysBusiness.odontologoWS.modificarOdontologoResponse OdontoSysBusiness.odontologoWS.Odontologos.modificarOdontologo(OdontoSysBusiness.odontologoWS.modificarOdontologoRequest request) {
            return base.Channel.modificarOdontologo(request);
        }
        
        public int modificarOdontologo(OdontoSysBusiness.odontologoWS.odontologo odontologo) {
            OdontoSysBusiness.odontologoWS.modificarOdontologoRequest inValue = new OdontoSysBusiness.odontologoWS.modificarOdontologoRequest();
            inValue.odontologo = odontologo;
            OdontoSysBusiness.odontologoWS.modificarOdontologoResponse retVal = ((OdontoSysBusiness.odontologoWS.Odontologos)(this)).modificarOdontologo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OdontoSysBusiness.odontologoWS.modificarOdontologoResponse> OdontoSysBusiness.odontologoWS.Odontologos.modificarOdontologoAsync(OdontoSysBusiness.odontologoWS.modificarOdontologoRequest request) {
            return base.Channel.modificarOdontologoAsync(request);
        }
        
        public System.Threading.Tasks.Task<OdontoSysBusiness.odontologoWS.modificarOdontologoResponse> modificarOdontologoAsync(OdontoSysBusiness.odontologoWS.odontologo odontologo) {
            OdontoSysBusiness.odontologoWS.modificarOdontologoRequest inValue = new OdontoSysBusiness.odontologoWS.modificarOdontologoRequest();
            inValue.odontologo = odontologo;
            return ((OdontoSysBusiness.odontologoWS.Odontologos)(this)).modificarOdontologoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OdontoSysBusiness.odontologoWS.listarPorEspecialidadResponse OdontoSysBusiness.odontologoWS.Odontologos.listarPorEspecialidad(OdontoSysBusiness.odontologoWS.listarPorEspecialidadRequest request) {
            return base.Channel.listarPorEspecialidad(request);
        }
        
        public OdontoSysBusiness.odontologoWS.odontologo[] listarPorEspecialidad(OdontoSysBusiness.odontologoWS.especialidad especialidad) {
            OdontoSysBusiness.odontologoWS.listarPorEspecialidadRequest inValue = new OdontoSysBusiness.odontologoWS.listarPorEspecialidadRequest();
            inValue.especialidad = especialidad;
            OdontoSysBusiness.odontologoWS.listarPorEspecialidadResponse retVal = ((OdontoSysBusiness.odontologoWS.Odontologos)(this)).listarPorEspecialidad(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OdontoSysBusiness.odontologoWS.listarPorEspecialidadResponse> OdontoSysBusiness.odontologoWS.Odontologos.listarPorEspecialidadAsync(OdontoSysBusiness.odontologoWS.listarPorEspecialidadRequest request) {
            return base.Channel.listarPorEspecialidadAsync(request);
        }
        
        public System.Threading.Tasks.Task<OdontoSysBusiness.odontologoWS.listarPorEspecialidadResponse> listarPorEspecialidadAsync(OdontoSysBusiness.odontologoWS.especialidad especialidad) {
            OdontoSysBusiness.odontologoWS.listarPorEspecialidadRequest inValue = new OdontoSysBusiness.odontologoWS.listarPorEspecialidadRequest();
            inValue.especialidad = especialidad;
            return ((OdontoSysBusiness.odontologoWS.Odontologos)(this)).listarPorEspecialidadAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OdontoSysBusiness.odontologoWS.od_buscarPorUsuarioResponse OdontoSysBusiness.odontologoWS.Odontologos.od_buscarPorUsuario(OdontoSysBusiness.odontologoWS.od_buscarPorUsuarioRequest request) {
            return base.Channel.od_buscarPorUsuario(request);
        }
        
        public OdontoSysBusiness.odontologoWS.odontologo od_buscarPorUsuario(string odontologoUsuario) {
            OdontoSysBusiness.odontologoWS.od_buscarPorUsuarioRequest inValue = new OdontoSysBusiness.odontologoWS.od_buscarPorUsuarioRequest();
            inValue.odontologoUsuario = odontologoUsuario;
            OdontoSysBusiness.odontologoWS.od_buscarPorUsuarioResponse retVal = ((OdontoSysBusiness.odontologoWS.Odontologos)(this)).od_buscarPorUsuario(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OdontoSysBusiness.odontologoWS.od_buscarPorUsuarioResponse> OdontoSysBusiness.odontologoWS.Odontologos.od_buscarPorUsuarioAsync(OdontoSysBusiness.odontologoWS.od_buscarPorUsuarioRequest request) {
            return base.Channel.od_buscarPorUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<OdontoSysBusiness.odontologoWS.od_buscarPorUsuarioResponse> od_buscarPorUsuarioAsync(string odontologoUsuario) {
            OdontoSysBusiness.odontologoWS.od_buscarPorUsuarioRequest inValue = new OdontoSysBusiness.odontologoWS.od_buscarPorUsuarioRequest();
            inValue.odontologoUsuario = odontologoUsuario;
            return ((OdontoSysBusiness.odontologoWS.Odontologos)(this)).od_buscarPorUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OdontoSysBusiness.odontologoWS.od_listarOdontologosResponse OdontoSysBusiness.odontologoWS.Odontologos.od_listarOdontologos(OdontoSysBusiness.odontologoWS.od_listarOdontologosRequest request) {
            return base.Channel.od_listarOdontologos(request);
        }
        
        public OdontoSysBusiness.odontologoWS.odontologo[] od_listarOdontologos() {
            OdontoSysBusiness.odontologoWS.od_listarOdontologosRequest inValue = new OdontoSysBusiness.odontologoWS.od_listarOdontologosRequest();
            OdontoSysBusiness.odontologoWS.od_listarOdontologosResponse retVal = ((OdontoSysBusiness.odontologoWS.Odontologos)(this)).od_listarOdontologos(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OdontoSysBusiness.odontologoWS.od_listarOdontologosResponse> OdontoSysBusiness.odontologoWS.Odontologos.od_listarOdontologosAsync(OdontoSysBusiness.odontologoWS.od_listarOdontologosRequest request) {
            return base.Channel.od_listarOdontologosAsync(request);
        }
        
        public System.Threading.Tasks.Task<OdontoSysBusiness.odontologoWS.od_listarOdontologosResponse> od_listarOdontologosAsync() {
            OdontoSysBusiness.odontologoWS.od_listarOdontologosRequest inValue = new OdontoSysBusiness.odontologoWS.od_listarOdontologosRequest();
            return ((OdontoSysBusiness.odontologoWS.Odontologos)(this)).od_listarOdontologosAsync(inValue);
        }
    }
}
